var tempArray = new Array();

tempArray.push('Encore Paving')
tempArray.push('Pave The Way Inc')
tempArray.push('Dans Water and Sewer')
tempArray.push('Evergy-ICT')
tempArray.push('AT&T Tech Operations')
tempArray.push('Albertson Associates LLC')
tempArray.push('Conseptos Concrete')
tempArray.push('Black Hills')
tempArray.push('Cox Communications')
tempArray.push('Wichita Sewer Department')
tempArray.push('Wichita Water Utilities & Dist')
tempArray.push('Westar ICT')
tempArray.push('Zayo Group Accounts Payable')
tempArray.push('One Gas INC (KGS)')
tempArray.push('Rock Concrete')
tempArray.push('Opp Concrete')
tempArray.push('Ortiz Construction')
tempArray.push('AT & T  (SBC)')
tempArray.push('Voegeli,James Construction Inc')
tempArray.push('B & R Construction')
tempArray.push('Betzen Trenching')
tempArray.push('CK Contracting LLC.')
tempArray.push('Wichita Electric Company Inc')
tempArray.push('David Lies Plumbing Inc.')
tempArray.push('Old Town plumbing')
tempArray.push('Benjamin  Franklin Plumbing')
tempArray.push('Plumbing Solutions of Wichita')
tempArray.push('McCullough Exc.')
tempArray.push('McGuire Flatwork and Grading')
tempArray.push('Circle C Paving & Construction')
tempArray.push('Triple C Concrete LLC')
tempArray.push('Mr Rooter Plumbing')
tempArray.push('Montes Construction')
tempArray.push('Ricky C Const.')
tempArray.push('G-Mac Construction')
tempArray.push('Olvera Concrete')
tempArray.push('Montanez Construction Concrete')
tempArray.push('Gulick Const.')
tempArray.push('Corrado Concrete & Constructio')
tempArray.push('Ricalday Construction')
tempArray.push('Key Construction')
tempArray.push('Bower Concrete')
tempArray.push('McColm Construction')
tempArray.push('Evergy')
tempArray.push('Morgan Cement')
tempArray.push('Heartstone Inc.')
tempArray.push('Winter Concrete')
tempArray.push('Rodriguez Flat Work Concrete')
tempArray.push('APAC-Kansas')
tempArray.push('Law Company, The')
tempArray.push('C&A Concrete & Dirt Works')
tempArray.push('SmithCon')
tempArray.push('Thonen and Son')
tempArray.push('KDHE')
tempArray.push('Phillips 66 Pipeline LLC')
tempArray.push('Evans Building Co. Inc')
tempArray.push('Farha Construction')
tempArray.push('CARDNO ATC')
tempArray.push('Property Owner')
tempArray.push('A&J Construction')
tempArray.push('Environmental Health')
tempArray.push('BCM')
tempArray.push('Ewertz Excavation')
tempArray.push('Southern Star Pipeline')
tempArray.push('Diamond Engineering')
tempArray.push('M H Development LLC')
tempArray.push('NuStar PL Operating partin')
tempArray.push('Diaz Construction')
tempArray.push('Holland Paving')
tempArray.push('Colin Busey')
tempArray.push('David Reep')
tempArray.push('All Year Contractors')
tempArray.push('Engineering Division')
tempArray.push('Karst Garages INC')
tempArray.push('PHILLIPS 66 COMPANY')
tempArray.push('Penner Construction Svcs')
tempArray.push('Jose Luis Martinez-Cornejo')
tempArray.push('Hiser Contracting')
tempArray.push('Ryan Stephan')
tempArray.push('Mies Construction')
tempArray.push('Vogts-Parga Construction')
tempArray.push('Associated Environmental, Inc.')
tempArray.push('Quality Construction LLC')
tempArray.push('Breckco Construction')
tempArray.push('Bob The Sewer Guy')
tempArray.push('Wilks Underground Utilities LL')
tempArray.push('Simpson Construction Services')
tempArray.push('Fire Protection Services')
tempArray.push('Commercial Mechanical Inc.')
tempArray.push('Beran Concrete Inc.')
tempArray.push('Santana Construction')
tempArray.push('Padgett Excavation Inc.')
tempArray.push('A&D Total Plumbing')
tempArray.push('Custom Flatwork')
tempArray.push('Reed Plumbing Services LLC')
tempArray.push('Emergency Sewer Repair')
tempArray.push('Nowak Construction Co. Inc.')
tempArray.push('Lucio Castillo-Lara')
tempArray.push('Wildcat Construction Inc,')
tempArray.push('Smith Construction Company Inc')
tempArray.push('Brad Murray Inc.')
tempArray.push('Douglas Winter')
tempArray.push('Wichita Engineering Division')
tempArray.push('Mac Pherson Construction')
tempArray.push('Wichita Storm Water Utilities')
tempArray.push('COW Street Maintenance')
tempArray.push('Bader Construction')
tempArray.push('Conco Construction')
tempArray.push('Vazquez & Sons')
tempArray.push('B & B Builders')
tempArray.push('Manuel Olguin')
tempArray.push('Cornejo & Sons')
tempArray.push('Major Concrete Inc.')
tempArray.push('Daniel Haskins')
tempArray.push('Dunkelberger Construction Co.')
tempArray.push('Rich Construction')
tempArray.push('Darl Christner')
tempArray.push('Steve Kemp Concrete Const.')
tempArray.push('Salas Construction')
tempArray.push('New Era Construction')
tempArray.push('P&W Inc DBA Roto Rooter')
tempArray.push('Cochran Enterprises LLC')
tempArray.push('SCS ENGINEERS')
tempArray.push('Mike Powell')
tempArray.push('S & V Concrete')
tempArray.push('Lyon Const.')
tempArray.push('MY Construction')
tempArray.push('Quality Concrete Solutions')
tempArray.push('E&J Concrete')
tempArray.push('Kansas Paving')
tempArray.push('Coleman Construction Co.')
tempArray.push('Arambula Construction Co.')
tempArray.push('Commerce Construction Services')
tempArray.push('Larsen & Associates Inc.')
tempArray.push('Garrison Concrete Construction')
tempArray.push('Big Sons Construction Co')
tempArray.push('Beard  & Son')
tempArray.push('Barkley Construction')
tempArray.push('Banzet Concrete Inc.')
tempArray.push('Rochel Concrete')
tempArray.push('PP & J Construction')
tempArray.push('Canos Concrete LLC')
tempArray.push('Bob Cook Homes LLC.')
tempArray.push('Dondlinger & Sons Construction')
tempArray.push('American Services')
tempArray.push('CB&I INC')
tempArray.push('Goshen Property Management LLC')
tempArray.push('Evergy TOP')
tempArray.push('Progressive Ins')
tempArray.push('Trejo Const.')
tempArray.push('Reddi Industries')
tempArray.push('Innovative Concrete Concepts')
tempArray.push('Always Plumbing')
tempArray.push('Angels Construction')
tempArray.push('Perez Concrete Construction')
tempArray.push('Elite Concrete Inc.')
tempArray.push('Gulick')
tempArray.push('Roncrete')
tempArray.push('Guerreros Concrete')
tempArray.push('HD Mills & Sons')
tempArray.push('Utilities Plus')
tempArray.push('Colemans Flatwork')
tempArray.push('Arambula Drain & Sewer')
tempArray.push('Don Vaughn Inc.')
tempArray.push('Wichita Excavation')
tempArray.push('Heinz Construction')
tempArray.push('The Concrete Guys')
tempArray.push('USD 259')
tempArray.push('Surface Protection Services LL')
tempArray.push('Love Construction')
tempArray.push('J & C  Concrete Construction')
tempArray.push('All American Concrete')
tempArray.push('A Avitia')
tempArray.push('Wolf Construction Inc')
tempArray.push('Traffic Engineering')
tempArray.push('Tozzies Drain Cleaning')
tempArray.push('Graber Backhoe Inc')
tempArray.push('Quantity Adjustment')
tempArray.push('Level 3 Communications')
tempArray.push('Phillips Southern Electric Co.')
tempArray.push('Martin K Eby Construction Co')
tempArray.push('Parrent LLC')
tempArray.push('Drain Pros')
tempArray.push('Poor Pappy\s Plumbing')
tempArray.push('Romani Construction')
tempArray.push('Johnson Controls')
tempArray.push('Intrust Arena')
tempArray.push('Dutton Construction')
tempArray.push('Kansas Fiber Network LLC')
tempArray.push('A Bader Company')
tempArray.push('BIG RIVER CONSTRUCTION')
tempArray.push('Richards EarthWorks')
tempArray.push('GeoCore Inc.')
tempArray.push('Guzman Construction')
tempArray.push('Fidelity Bank')
tempArray.push('Wichita Water IT Dirt Cut')
tempArray.push('GSI LLC')
tempArray.push('Below Ground Surface Inc')
tempArray.push('Penner Cement')
tempArray.push('Blu Rock')
tempArray.push('Javen Brown Construction LLC')
tempArray.push('Brand Plumbing Inc.')
tempArray.push('Midwest Fire Protection')
tempArray.push('Oakridge Construction Services')
tempArray.push('Ortega and Sons Concrete')
tempArray.push('Environmental Priority Service')
tempArray.push('Standard Construction')
tempArray.push('Pearson Construction LLC')
tempArray.push('A E Henning')
tempArray.push('JTT Concrete and Landscaping')
tempArray.push('M&G & Sons Construction')
tempArray.push('Park Dept')
tempArray.push('Eby Corp')
tempArray.push('Cutting Edge Concrete Cutting')
tempArray.push('Andale Construction')
tempArray.push('Fahnestock HVAC Plumbing')
tempArray.push('Mark Sullentrop')
tempArray.push('Superior Exterior LLC')
tempArray.push('CDH Incorporated')
tempArray.push('EMR')
tempArray.push('CDK Distribution LLC')
tempArray.push('Strong Hand')
tempArray.push('Roberts Concrete LLC')
tempArray.push('MT Construction LLC')
tempArray.push('TRC Solutions')
tempArray.push('Rapid Services LLC')
tempArray.push('Newfarmer Excavation INC')
tempArray.push('Triple B Construction Inc')
tempArray.push('Bowers Plumbing')
tempArray.push('Midwest Foam Works')
tempArray.push('P1 Service')
tempArray.push('Henning Constr Services LLC')
tempArray.push('3 Mendozas Concrete')
tempArray.push('Arcadis U.S. Inc')
tempArray.push('On Time Plumbing')
tempArray.push('Kaw Valley Engineering, Inc')
tempArray.push('316 Paving & Construction LLC')
tempArray.push('Jerry Lies Trenching PC')
tempArray.push('Carrs Plumbing')
tempArray.push('Jerry Wells')
tempArray.push('Hutton Construction')
tempArray.push('DeLeon Concrete Construction')
tempArray.push('Idelco LLC')
tempArray.push('Roto Rooter Plumbers')
tempArray.push('ICT Caliber Concrete LLC')
tempArray.push('MW Plumbing')
tempArray.push('Duling Construction Co Inc')
tempArray.push('Waldinger Corporation')
tempArray.push('Professional Mechanical Contra')
tempArray.push('Salas Plumbing and Remodeling')
tempArray.push('Sooter Excavating')
tempArray.push('Shallup Plumbing LLC')
tempArray.push('Mobilitie')
tempArray.push('Adames Concrete')
tempArray.push('1NE Services Solutions')
tempArray.push('Prado Construction')
tempArray.push('Sedgwick County Electric Coop')
tempArray.push('Acme Construction')
tempArray.push('Allied Environmental')
tempArray.push('Landis Concrete Construction')
tempArray.push('Studium Build LLC')
tempArray.push('Braun Intertec Corp')
tempArray.push('Black & McDonald')
tempArray.push('Espinoza Arturo')
tempArray.push('Belford Electric')
tempArray.push('Noel Masonary & Concrete LLC')
tempArray.push('New Step Construction LLC')
tempArray.push('Always Plumbing')
tempArray.push('Sturdy Built Const. & Demo LLC')
tempArray.push('Sifuentes Concrete')
tempArray.push('D&R Plumbing')
tempArray.push('Wichita Construction Group')
tempArray.push('Utility Maintenance Contractor')
tempArray.push('Apex Excavating')
tempArray.push('Ideatek')
tempArray.push('Freestyle Sign Company Inc')
tempArray.push('KCC Construction LLC')
tempArray.push('Harbinger Concrete Constr')
tempArray.push('Bill Cummings')
tempArray.push('O & O Construction LLC')
tempArray.push('D&A Construction')
tempArray.push('Selective Site Consultants Inc')
tempArray.push('MSR Construction')
tempArray.push('Rupe Helmer Group')
tempArray.push('Terracon Consultants Inc')
tempArray.push('South Central Sealing')
tempArray.push('Campos & Sons Concrete LLC')
tempArray.push('Polo Concrete LLC')
tempArray.push('Amigo Excavation and Plumbing')
tempArray.push('More Store @ 143rd LLC')
tempArray.push('Unlimited Top Notch Services')
tempArray.push('Browns Plumbing Service')
tempArray.push('Ruiz Construction')
tempArray.push('Precision Plumbing')
tempArray.push('Rodriguez Concrete')
tempArray.push('Martsolf Enterprises LLC')
tempArray.push('Robs Asphalt Paving and Seal')
tempArray.push('Baldaras Construction')
tempArray.push('Premier Landscape')
tempArray.push('Longhorn Construction')
tempArray.push('Olson Sewer Services')
tempArray.push('Iguanas Construction')
tempArray.push('Christian Heimerman')
tempArray.push('Layne Christensen')
tempArray.push('Double R Construction LLC')
tempArray.push('Larraga Flatwork')
tempArray.push('AK Construction')
tempArray.push('GN Plumbing LLC')
tempArray.push('Multicrete')
tempArray.push('Pathfinder HDD')
tempArray.push('Innocon Construction')
tempArray.push('CG Construction & Remodeling')
tempArray.push('Midwest Management')
tempArray.push('L&P Concrete')
tempArray.push('New Life Flatwork')
tempArray.push('Lyday Plumbing')
tempArray.push('Chris Schiller')
tempArray.push('Beachy Contractors LLC')
tempArray.push('Beavers Plumbing LLC')
tempArray.push('Apollo Concrete')
tempArray.push('Western Group')
tempArray.push('Twins Masonry')
tempArray.push('Raphael Diaz')
tempArray.push('Bar T Concrete')
tempArray.push('Plain Keeper Construction LLC')
tempArray.push('J&L Exquisite Services')
tempArray.push('Campos ICT Concrete LLC')
tempArray.push('RMC Construction')
tempArray.push('Wichita Home Works')
tempArray.push('Verizon Communications')
tempArray.push('Habitat Architects LLC')
tempArray.push('Luna Concrete Construction')
tempArray.push('316 Concrete')
tempArray.push('Concrete Services')
tempArray.push('Scott C Wright')
tempArray.push('Unique Concrete Creations')
tempArray.push('Jeff Longwell')
tempArray.push('J & JR Concrete')
tempArray.push('K&B Dirtworks')
tempArray.push('MVM Construction')
tempArray.push('Leos Concrete')
tempArray.push('Your Favorite Plumber')
tempArray.push('Greenfield Contractors')
tempArray.push('Ballard Plumbing')
tempArray.push('Perche Concrete Construction')
tempArray.push('Varsity Construction')
tempArray.push('Icon Structures')
tempArray.push('Core Contractors')
tempArray.push('RF Magon Construction')
tempArray.push('Leyva Construction')
tempArray.push('G&I Concrete')
tempArray.push('Prosite Restoration & Const')
tempArray.push('Plumb Crazy')
tempArray.push('Aptim Environmental & Infrastr')
tempArray.push('Aptim')
tempArray.push('NLC Construction')
tempArray.push('LMV Concrete')
tempArray.push('Electri-Tech Inc')
tempArray.push('Stuart Ray')
tempArray.push('One Source Home Services')
tempArray.push('SIRZ Concrete')
tempArray.push('Tom Concrete')
tempArray.push('Casta Construction')
tempArray.push('Soyates Concrete')
tempArray.push('Plains Environmental Services')
tempArray.push('ASAP Plumbing & Construction')
tempArray.push('ACON Concrete Construction')



for (i in tempArray){

    // logDebug(tempArray[i][0])
    // logDebug(tempArray[i][1])

    addLookup('ENG_UTIL_APPLICANT', tempArray[i], tempArray[i] )

}

function addLookup(stdChoice,stdValue,stdDesc) 
	{
	//check if stdChoice and stdValue already exist; if they do, don't add
	var bizDomScriptResult = aa.bizDomain.getBizDomainByValue(stdChoice,stdValue);
	if (bizDomScriptResult.getSuccess())
		{
		logDebug("Standard Choices Item "+stdChoice+" and Value "+stdValue+" already exist.  Lookup is not added or updated.");
		return false;
		}
	//Proceed to add
	var strControl;
	
	if (stdChoice != null && stdChoice.length && stdValue != null && stdValue.length && stdDesc != null && stdDesc.length)
		{
		var bizDomScriptResult = aa.bizDomain.createBizDomain(stdChoice, stdValue, "A", stdDesc)
		if (bizDomScriptResult.getSuccess())
			//check if new Std Choice actually created

			logDebug("Successfully created Std Choice(" + stdChoice + "," + stdValue + ") = " + stdDesc);
		else
			logDebug("**ERROR creating Std Choice " + bizDomScriptResult.getErrorMessage());
		}
	else
		logDebug("Could not create std choice, one or more null values");
	}

    function logDebug(str){
        aa.print(str);
    }