USE [EMCITY_SUPP]
GO
/****** Object:  UserDefinedFunction [dbo].[ATT_TO_NUMBER]    Script Date: 1/26/2023 2:44:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER   FUNCTION [dbo].[ATT_TO_NUMBER]
( @P_L1_ATTRIBUTE_VALUE varchar(4000)
) RETURNS FLOAT(36)
AS 
BEGIN
   DECLARE 
      @V_L1_ATTRIBUTE_VALUE_NUM FLOAT(36) = NULL

   IF ISNUMERIC(@P_L1_ATTRIBUTE_VALUE)=1
     SET @V_L1_ATTRIBUTE_VALUE_NUM = CONVERT(FLOAT(36), @P_L1_ATTRIBUTE_VALUE)
     
   RETURN @V_L1_ATTRIBUTE_VALUE_NUM

END
