/* 	AMT_Agency_Delete_PartialTransactions-Sarasota_SSMS.sql
	2022.10.18 MKH - Copied from AMT_Agency_Delete_PartialTransactions-MULTI.sql and modified to execute under SSMS.  Edit declare statements for your agency.
	2022.10.18 MKH - Added section at bottom for removal of RACCOUNT and F4ACCT_TRANSACTION data for Sarasota.  Adjust or remove for your agency.
 */
USE SCMN_SUPP;													-- Enter target database for this remove script
SET QUOTED_IDENTIFIER ON;

DECLARE @SPC VARCHAR(30) = 'SCMN';								-- Agency SERV_PROV_CODE
DECLARE @PREDICATE varchar(max) = 'SERV_PROV_CODE = ''SCMN'''; 	-- Agency WHERE clause logic
PRINT @PREDICATE;

--SET @PREDICATE = CAST(CAST(N'' AS XML).value('xs:base64Binary(sql:variable("@PREDICATE"))','varbinary(max)') AS nvarchar(max));
DECLARE @sql nvarchar(max)

DROP TABLE IF EXISTS #REMOVE_PER_LIST;
DROP TABLE IF EXISTS #REMOVE_PER_LIST_INVOICE;
DROP TABLE IF EXISTS #REMOVE_PER_LIST_RECEIPT;

SELECT SERV_PROV_CODE,B1_PER_ID1,B1_PER_ID2,B1_PER_ID3,B1_ALT_ID INTO #REMOVE_PER_LIST FROM B1PERMIT WHERE 1=2;
SET @sql = N'INSERT INTO #REMOVE_PER_LIST(SERV_PROV_CODE,B1_PER_ID1,B1_PER_ID2,B1_PER_ID3,B1_ALT_ID) SELECT SERV_PROV_CODE,B1_PER_ID1,B1_PER_ID2,B1_PER_ID3,B1_ALT_ID FROM B1PERMIT WHERE ' + @PREDICATE;
PRINT @SQL;

EXEC sp_executesql @sql
 
CREATE INDEX REMOVE_PER_LIST_X01 ON #REMOVE_PER_LIST(SERV_PROV_CODE,B1_PER_ID1,B1_PER_ID2,B1_PER_ID3);
 
SELECT DISTINCT 
       A.SERV_PROV_CODE,
	   A.INVOICE_NBR 
  INTO #REMOVE_PER_LIST_INVOICE
  FROM X4FEEITEM_INVOICE A,
       #REMOVE_PER_LIST B 
 WHERE A.SERV_PROV_CODE=B.SERV_PROV_CODE
   AND A.B1_PER_ID1=B.B1_PER_ID1
   AND A.B1_PER_ID2=B.B1_PER_ID2
   AND A.B1_PER_ID3=B.B1_PER_ID3;

CREATE INDEX REMOVE_PER_LIST_INVOICE_X01 ON #REMOVE_PER_LIST_INVOICE(SERV_PROV_CODE,INVOICE_NBR);

SELECT DISTINCT 
       A.SERV_PROV_CODE,
	   A.RECEIPT_NBR 
  INTO #REMOVE_PER_LIST_RECEIPT
  FROM F4PAYMENT A,
       #REMOVE_PER_LIST B 
 WHERE A.SERV_PROV_CODE=B.SERV_PROV_CODE
   AND A.B1_PER_ID1=B.B1_PER_ID1
   AND A.B1_PER_ID2=B.B1_PER_ID2
   AND A.B1_PER_ID3=B.B1_PER_ID3;

CREATE INDEX REMOVE_PER_LIST_RECEIPT_X01 ON #REMOVE_PER_LIST_RECEIPT(SERV_PROV_CODE,RECEIPT_NBR);

-------------------------------------------------
--DELETE SCRIPT START HERE-----------------------
-------------------------------------------------

PRINT 'DELETE FROM MRULIST';
PRINT '------------------------------------------';
DELETE FROM MRULIST
WHERE SERV_PROV_CODE= 'SCMN' AND ENTITY_TYPE LIKE '%CAP%' 
AND ENTITY_ID IN (SELECT 'serviceProviderCode='+serv_prov_code+'|'+'ID1='+b1_per_id1+'|ID2='+B1_pER_ID2+'|ID3='+B1_PER_ID3
FROM #REMOVE_PER_LIST);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM GEDUCATION';
PRINT '------------------------------------------';
DELETE FROM GEDUCATION
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GEDUCATION.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GEDUCATION.B1_PER_ID1 = B.B1_PER_ID1
    AND GEDUCATION.B1_PER_ID2 = B.B1_PER_ID2
    AND GEDUCATION.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM X4TRANS_FEEITEM';
PRINT '------------------------------------------';
DELETE FROM X4TRANS_FEEITEM
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE X4TRANS_FEEITEM.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND X4TRANS_FEEITEM.B1_PER_ID1 = B.B1_PER_ID1
    AND X4TRANS_FEEITEM.B1_PER_ID2 = B.B1_PER_ID2
    AND X4TRANS_FEEITEM.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM GCONT_EDU';
PRINT '------------------------------------------';
DELETE FROM GCONT_EDU
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GCONT_EDU.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GCONT_EDU.B1_PER_ID1 = B.B1_PER_ID1
    AND GCONT_EDU.B1_PER_ID2 = B.B1_PER_ID2
    AND GCONT_EDU.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM B7RANDOM_AUDIT'
PRINT '-----------------------------------------';
DELETE FROM B7RANDOM_AUDIT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE B7RANDOM_AUDIT.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND B7RANDOM_AUDIT.B1_PER_ID1 = B.B1_PER_ID1
    AND B7RANDOM_AUDIT.B1_PER_ID2 = B.B1_PER_ID2
    AND B7RANDOM_AUDIT.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted'
PRINT '------------------------------------------';

PRINT 'DELETE FROM GEXAM';
PRINT '------------------------------------------';
DELETE FROM GEXAM
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GEXAM.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GEXAM.B1_PER_ID1 = B.B1_PER_ID1
    AND GEXAM.B1_PER_ID2 = B.B1_PER_ID2
    AND GEXAM.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM XCOLLECTION_BPERMIT';
PRINT '------------------------------------------';
DELETE FROM XCOLLECTION_BPERMIT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE XCOLLECTION_BPERMIT.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND XCOLLECTION_BPERMIT.B1_PER_ID1 = B.B1_PER_ID1
    AND XCOLLECTION_BPERMIT.B1_PER_ID2 = B.B1_PER_ID2
    AND XCOLLECTION_BPERMIT.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM FSHOPPING_CART_ITEM';
PRINT '------------------------------------------';
DELETE FROM FSHOPPING_CART_ITEM
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE FSHOPPING_CART_ITEM.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND FSHOPPING_CART_ITEM.B1_PER_ID1 = B.B1_PER_ID1
    AND FSHOPPING_CART_ITEM.B1_PER_ID2 = B.B1_PER_ID2
    AND FSHOPPING_CART_ITEM.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM AGIS_OBJECT_ENT';
PRINT '------------------------------------------';
DELETE FROM AGIS_OBJECT_ENT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B, RSERV_PROV RP
  WHERE RP.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND AGIS_OBJECT_ENT.B1_PER_ID1 = B.B1_PER_ID1
    AND AGIS_OBJECT_ENT.B1_PER_ID2 = B.B1_PER_ID2
    AND AGIS_OBJECT_ENT.B1_PER_ID3 = B.B1_PER_ID3
	AND AGIS_OBJECT_ENT.AGENCY = RP.APO_SRC_SEQ_NBR
    --AND AGIS_OBJECT_ENT.AGENCY = TO_CHAR(RP.APO_SRC_SEQ_NBR)
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM B3ADDRES_DISTRICT';
PRINT '------------------------------------------';
DELETE FROM B3ADDRES_DISTRICT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE B3ADDRES_DISTRICT.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND B3ADDRES_DISTRICT.B1_PER_ID1 = B.B1_PER_ID1
    AND B3ADDRES_DISTRICT.B1_PER_ID2 = B.B1_PER_ID2
    AND B3ADDRES_DISTRICT.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM B3ADDRES_TYPE';
PRINT '------------------------------------------';
DELETE FROM B3ADDRES_TYPE
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE B3ADDRES_TYPE.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND B3ADDRES_TYPE.B1_PER_ID1 = B.B1_PER_ID1
    AND B3ADDRES_TYPE.B1_PER_ID2 = B.B1_PER_ID2
    AND B3ADDRES_TYPE.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM B3PARCEL_DISTRICT';
PRINT '------------------------------------------';
DELETE FROM B3PARCEL_DISTRICT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE B3PARCEL_DISTRICT.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND B3PARCEL_DISTRICT.B1_PER_ID1 = B.B1_PER_ID1
    AND B3PARCEL_DISTRICT.B1_PER_ID2 = B.B1_PER_ID2
    AND B3PARCEL_DISTRICT.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM B3STRU_ESTA';
PRINT '------------------------------------------';
DELETE FROM B3STRU_ESTA
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE B3STRU_ESTA.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND B3STRU_ESTA.B1_PER_ID1 = B.B1_PER_ID1
    AND B3STRU_ESTA.B1_PER_ID2 = B.B1_PER_ID2
    AND B3STRU_ESTA.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM B6CONDIT_DETAIL';
PRINT '------------------------------------------';
DELETE FROM B6CONDIT_DETAIL
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE B6CONDIT_DETAIL.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND B6CONDIT_DETAIL.B1_PER_ID1 = B.B1_PER_ID1
    AND B6CONDIT_DETAIL.B1_PER_ID2 = B.B1_PER_ID2
    AND B6CONDIT_DETAIL.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM BAPPSPECTABLE_VALUE';
PRINT '------------------------------------------';
DELETE FROM BAPPSPECTABLE_VALUE
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE BAPPSPECTABLE_VALUE.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND BAPPSPECTABLE_VALUE.B1_PER_ID1 = B.B1_PER_ID1
    AND BAPPSPECTABLE_VALUE.B1_PER_ID2 = B.B1_PER_ID2
    AND BAPPSPECTABLE_VALUE.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM BAPPSPECTABLE';
PRINT '------------------------------------------';
DELETE FROM BAPPSPECTABLE
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE BAPPSPECTABLE.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND BAPPSPECTABLE.B1_PER_ID1 = B.B1_PER_ID1
    AND BAPPSPECTABLE.B1_PER_ID2 = B.B1_PER_ID2
    AND BAPPSPECTABLE.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM BCALC_VALUATN_HISTORY';
PRINT '------------------------------------------';
DELETE FROM BCALC_VALUATN_HISTORY
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE BCALC_VALUATN_HISTORY.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND BCALC_VALUATN_HISTORY.B1_PER_ID1 = B.B1_PER_ID1
    AND BCALC_VALUATN_HISTORY.B1_PER_ID2 = B.B1_PER_ID2
    AND BCALC_VALUATN_HISTORY.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM BEVIDENCE_HISTORY';
PRINT '------------------------------------------';
DELETE FROM BEVIDENCE_HISTORY
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE BEVIDENCE_HISTORY.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND BEVIDENCE_HISTORY.B1_PER_ID1 = B.B1_PER_ID1
    AND BEVIDENCE_HISTORY.B1_PER_ID2 = B.B1_PER_ID2
    AND BEVIDENCE_HISTORY.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM BEVIDENCE';
PRINT '------------------------------------------';
DELETE FROM BEVIDENCE
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE BEVIDENCE.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND BEVIDENCE.B1_PER_ID1 = B.B1_PER_ID1
    AND BEVIDENCE.B1_PER_ID2 = B.B1_PER_ID2
    AND BEVIDENCE.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM BINFO_TABLE_VALUE'
PRINT '------------------------------------------';
DELETE FROM BINFO_TABLE_VALUE
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE BINFO_TABLE_VALUE.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND BINFO_TABLE_VALUE.B1_PER_ID1 = B.B1_PER_ID1
    AND BINFO_TABLE_VALUE.B1_PER_ID2 = B.B1_PER_ID2
    AND BINFO_TABLE_VALUE.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM BINFO_TABLE';
PRINT '------------------------------------------';
DELETE FROM BINFO_TABLE
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE BINFO_TABLE.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND BINFO_TABLE.B1_PER_ID1 = B.B1_PER_ID1
    AND BINFO_TABLE.B1_PER_ID2 = B.B1_PER_ID2
    AND BINFO_TABLE.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM GADDRESS_MAINTENANCE_TRACK';
PRINT '------------------------------------------';
DELETE FROM GADDRESS_MAINTENANCE_TRACK
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GADDRESS_MAINTENANCE_TRACK.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GADDRESS_MAINTENANCE_TRACK.B1_PER_ID1 = B.B1_PER_ID1
    AND GADDRESS_MAINTENANCE_TRACK.B1_PER_ID2 = B.B1_PER_ID2
    AND GADDRESS_MAINTENANCE_TRACK.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM GASSET_MAINTENANCE_TRACK';
PRINT '------------------------------------------';
DELETE FROM GASSET_MAINTENANCE_TRACK
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GASSET_MAINTENANCE_TRACK.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GASSET_MAINTENANCE_TRACK.B1_PER_ID1 = B.B1_PER_ID1
    AND GASSET_MAINTENANCE_TRACK.B1_PER_ID2 = B.B1_PER_ID2
    AND GASSET_MAINTENANCE_TRACK.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM GASSET_USAGE_TRACK';
PRINT '------------------------------------------';
DELETE FROM GASSET_USAGE_TRACK
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GASSET_USAGE_TRACK.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GASSET_USAGE_TRACK.B1_PER_ID1 = B.B1_PER_ID1
    AND GASSET_USAGE_TRACK.B1_PER_ID2 = B.B1_PER_ID2
    AND GASSET_USAGE_TRACK.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM GINSP_PROCESS';
PRINT '------------------------------------------';
DELETE FROM GINSP_PROCESS
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GINSP_PROCESS.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GINSP_PROCESS.B1_PER_ID1 = B.B1_PER_ID1
    AND GINSP_PROCESS.B1_PER_ID2 = B.B1_PER_ID2
    AND GINSP_PROCESS.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM GPART_TRANSACTION';
PRINT '------------------------------------------';
DELETE FROM GPART_TRANSACTION
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GPART_TRANSACTION.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GPART_TRANSACTION.B1_PER_ID1 = B.B1_PER_ID1
    AND GPART_TRANSACTION.B1_PER_ID2 = B.B1_PER_ID2
    AND GPART_TRANSACTION.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM GPM_SCHEDULE_LOG';
PRINT '------------------------------------------';
DELETE FROM GPM_SCHEDULE_LOG
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GPM_SCHEDULE_LOG.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GPM_SCHEDULE_LOG.B1_PER_ID1 = B.B1_PER_ID1
    AND GPM_SCHEDULE_LOG.B1_PER_ID2 = B.B1_PER_ID2
    AND GPM_SCHEDULE_LOG.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT '-----------------------------------------';
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted'

PRINT 'DELETE FROM GSEARCH_DATA';
PRINT '------------------------------------------';
DELETE FROM GSEARCH_DATA
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GSEARCH_DATA.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GSEARCH_DATA.B1_PER_ID1 = B.B1_PER_ID1
    AND GSEARCH_DATA.B1_PER_ID2 = B.B1_PER_ID2
    AND GSEARCH_DATA.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM GWORK_ORDER_ASSET';
PRINT '------------------------------------------';
DELETE FROM GWORK_ORDER_ASSET
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GWORK_ORDER_ASSET.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GWORK_ORDER_ASSET.B1_PER_ID1 = B.B1_PER_ID1
    AND GWORK_ORDER_ASSET.B1_PER_ID2 = B.B1_PER_ID2
    AND GWORK_ORDER_ASSET.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM GWORK_ORDER_TASK';
PRINT '------------------------------------------';
DELETE FROM GWORK_ORDER_TASK
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GWORK_ORDER_TASK.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GWORK_ORDER_TASK.B1_PER_ID1 = B.B1_PER_ID1
    AND GWORK_ORDER_TASK.B1_PER_ID2 = B.B1_PER_ID2
    AND GWORK_ORDER_TASK.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM T1_TIME_LOG';
PRINT '------------------------------------------';
DELETE FROM T1_TIME_LOG
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE T1_TIME_LOG.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND T1_TIME_LOG.B1_PER_ID1 = B.B1_PER_ID1
    AND T1_TIME_LOG.B1_PER_ID2 = B.B1_PER_ID2
    AND T1_TIME_LOG.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM X4SETPAYMENT';
PRINT '------------------------------------------';
DELETE FROM X4SETPAYMENT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE X4SETPAYMENT.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND X4SETPAYMENT.B1_PER_ID1 = B.B1_PER_ID1
    AND X4SETPAYMENT.B1_PER_ID2 = B.B1_PER_ID2
    AND X4SETPAYMENT.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM X4TRANS_PAYMENT';
PRINT '------------------------------------------';
DELETE FROM X4TRANS_PAYMENT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE X4TRANS_PAYMENT.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND X4TRANS_PAYMENT.B1_PER_ID1 = B.B1_PER_ID1
    AND X4TRANS_PAYMENT.B1_PER_ID2 = B.B1_PER_ID2
    AND X4TRANS_PAYMENT.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM XASSET_CA_WO';
PRINT '------------------------------------------';
DELETE FROM XASSET_CA_WO
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE XASSET_CA_WO.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND XASSET_CA_WO.B1_PER_ID1 = B.B1_PER_ID1
    AND XASSET_CA_WO.B1_PER_ID2 = B.B1_PER_ID2
    AND XASSET_CA_WO.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM XASSET_INSPECTION_WO'
PRINT '------------------------------------------';
DELETE FROM XASSET_INSPECTION_WO
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE XASSET_INSPECTION_WO.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND XASSET_INSPECTION_WO.B1_PER_ID1 = B.B1_PER_ID1
    AND XASSET_INSPECTION_WO.B1_PER_ID2 = B.B1_PER_ID2
    AND XASSET_INSPECTION_WO.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM XCONDIT_ACTION';
PRINT '------------------------------------------';
DELETE FROM XCONDIT_ACTION
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE XCONDIT_ACTION.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND XCONDIT_ACTION.B1_PER_ID1 = B.B1_PER_ID1
    AND XCONDIT_ACTION.B1_PER_ID2 = B.B1_PER_ID2
    AND XCONDIT_ACTION.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM XCONDIT_STATYP';
PRINT '------------------------------------------';
DELETE FROM XCONDIT_STATYP
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE XCONDIT_STATYP.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND XCONDIT_STATYP.B1_PER_ID1 = B.B1_PER_ID1
    AND XCONDIT_STATYP.B1_PER_ID2 = B.B1_PER_ID2
    AND XCONDIT_STATYP.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM BCAPWORKLOAD';
PRINT '------------------------------------------';
DELETE FROM BCAPWORKLOAD
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE BCAPWORKLOAD.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND BCAPWORKLOAD.B1_PER_ID1 = B.B1_PER_ID1
    AND BCAPWORKLOAD.B1_PER_ID2 = B.B1_PER_ID2
    AND BCAPWORKLOAD.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM STATUS_HISTORY';
PRINT '------------------------------------------';
DELETE FROM STATUS_HISTORY
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE STATUS_HISTORY.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND STATUS_HISTORY.B1_PER_ID1 = B.B1_PER_ID1
    AND STATUS_HISTORY.B1_PER_ID2 = B.B1_PER_ID2
    AND STATUS_HISTORY.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM GACTIVITY';
PRINT '------------------------------------------';
DELETE FROM GACTIVITY
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GACTIVITY.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GACTIVITY.B1_PER_ID1 = B.B1_PER_ID1
    AND GACTIVITY.B1_PER_ID2 = B.B1_PER_ID2
    AND GACTIVITY.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM XAPP2REF';
PRINT '------------------------------------------';
DELETE FROM XAPP2REF
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE XAPP2REF.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND XAPP2REF.B1_PER_ID1 = B.B1_PER_ID1
    AND XAPP2REF.B1_PER_ID2 = B.B1_PER_ID2
    AND XAPP2REF.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM GEXPIRATION_LOG';
PRINT '------------------------------------------';
DELETE FROM GEXPIRATION_LOG
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GEXPIRATION_LOG.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GEXPIRATION_LOG.B1_PER_ID1 = B.B1_PER_ID1
    AND GEXPIRATION_LOG.B1_PER_ID2 = B.B1_PER_ID2
    AND GEXPIRATION_LOG.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM XAPP_EVENT';
PRINT '------------------------------------------';
DELETE FROM XAPP_EVENT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE XAPP_EVENT.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND XAPP_EVENT.B1_PER_ID1 = B.B1_PER_ID1
    AND XAPP_EVENT.B1_PER_ID2 = B.B1_PER_ID2
    AND XAPP_EVENT.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '------------------------------------------';

PRINT 'DELETE FROM B1_EXPIRATION';
PRINT '------------------------------------------';
DELETE FROM B1_EXPIRATION
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE B1_EXPIRATION.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND B1_EXPIRATION.B1_PER_ID1 = B.B1_PER_ID1
    AND B1_EXPIRATION.B1_PER_ID2 = B.B1_PER_ID2
    AND B1_EXPIRATION.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM GGDSHEET_ITEM_ASITAB_VALUE';
PRINT '-----------------------------------------';
DELETE FROM GGDSHEET_ITEM_ASITAB_VALUE
WHERE EXISTS (
   SELECT '1' FROM #REMOVE_PER_LIST R, GGUIDESHEET G
   WHERE R.SERV_PROV_CODE = G.SERV_PROV_CODE
    AND R.B1_PER_ID1 = G.B1_PER_ID1
       AND R.B1_PER_ID2 = G.B1_PER_ID2
    AND R.B1_PER_ID3 = G.B1_PER_ID3
    AND G.SERV_PROV_CODE = GGDSHEET_ITEM_ASITAB_VALUE.SERV_PROV_CODE
    AND G.GUIDESHEET_SEQ_NBR = GGDSHEET_ITEM_ASITAB_VALUE.GUIDESHEET_SEQ_NBR
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM GGDSHEET_ITEM_ASITAB';
PRINT '-----------------------------------------';
DELETE FROM GGDSHEET_ITEM_ASITAB  
WHERE EXISTS (
   SELECT '1' FROM #REMOVE_PER_LIST R, GGUIDESHEET G 
   WHERE R.SERV_PROV_CODE = G.SERV_PROV_CODE
    AND R.B1_PER_ID1 = G.B1_PER_ID1
       AND R.B1_PER_ID2 = G.B1_PER_ID2
    AND R.B1_PER_ID3 = G.B1_PER_ID3
    AND G.SERV_PROV_CODE = GGDSHEET_ITEM_ASITAB.SERV_PROV_CODE
    AND G.GUIDESHEET_SEQ_NBR = GGDSHEET_ITEM_ASITAB.GUIDESHEET_SEQ_NBR
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM GGDSHEET_ITEM_ASI';
PRINT '-----------------------------------------';
DELETE FROM GGDSHEET_ITEM_ASI  
WHERE EXISTS (
   SELECT '1' FROM #REMOVE_PER_LIST R, GGUIDESHEET G 
   WHERE R.SERV_PROV_CODE = G.SERV_PROV_CODE
    AND R.B1_PER_ID1 = G.B1_PER_ID1
       AND R.B1_PER_ID2 = G.B1_PER_ID2
    AND R.B1_PER_ID3 = G.B1_PER_ID3
    AND G.SERV_PROV_CODE = GGDSHEET_ITEM_ASI.SERV_PROV_CODE
    AND G.GUIDESHEET_SEQ_NBR = GGDSHEET_ITEM_ASI.GUIDESHEET_SEQ_NBR
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM GGUIDESHEET_ITEM';
PRINT '-----------------------------------------';
DELETE FROM GGUIDESHEET_ITEM  
WHERE EXISTS (
   SELECT '1' FROM #REMOVE_PER_LIST R, GGUIDESHEET G
   WHERE R.SERV_PROV_CODE = G.SERV_PROV_CODE
    AND R.B1_PER_ID1 = G.B1_PER_ID1
       AND R.B1_PER_ID2 = G.B1_PER_ID2
    AND R.B1_PER_ID3 = G.B1_PER_ID3
    AND G.SERV_PROV_CODE = GGUIDESHEET_ITEM.SERV_PROV_CODE
    AND G.GUIDESHEET_SEQ_NBR = GGUIDESHEET_ITEM.GUIDESHEET_SEQ_NBR
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM GGUIDESHEET';
PRINT '-----------------------------------------';
DELETE FROM GGUIDESHEET
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GGUIDESHEET.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GGUIDESHEET.B1_PER_ID1 = B.B1_PER_ID1
    AND GGUIDESHEET.B1_PER_ID2 = B.B1_PER_ID2
    AND GGUIDESHEET.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM B1_SEC_TWN_RNG';
PRINT '-----------------------------------------';
DELETE FROM B1_SEC_TWN_RNG
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE B1_SEC_TWN_RNG.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND B1_SEC_TWN_RNG.B1_PER_ID1 = B.B1_PER_ID1
    AND B1_SEC_TWN_RNG.B1_PER_ID2 = B.B1_PER_ID2
    AND B1_SEC_TWN_RNG.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';
PRINT 'DELETE FROM GPROCESS_RPT';
PRINT '-----------------------------------------';
DELETE FROM GPROCESS_RPT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GPROCESS_RPT.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GPROCESS_RPT.B1_PER_ID1 = B.B1_PER_ID1
    AND GPROCESS_RPT.B1_PER_ID2 = B.B1_PER_ID2
    AND GPROCESS_RPT.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM GPROCESS_PROXIMITY_ALERTS';
PRINT '-----------------------------------------';
DELETE FROM GPROCESS_PROXIMITY_ALERTS
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GPROCESS_PROXIMITY_ALERTS.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GPROCESS_PROXIMITY_ALERTS.B1_PER_ID1 = B.B1_PER_ID1
    AND GPROCESS_PROXIMITY_ALERTS.B1_PER_ID2 = B.B1_PER_ID2
    AND GPROCESS_PROXIMITY_ALERTS.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM GPROCESS_PROXIMITY_ALERTS_AUT';
PRINT '-----------------------------------------';
DELETE FROM GPROCESS_PROXIMITY_ALERTS_AUT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GPROCESS_PROXIMITY_ALERTS_AUT.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GPROCESS_PROXIMITY_ALERTS_AUT.B1_PER_ID1 = B.B1_PER_ID1
    AND GPROCESS_PROXIMITY_ALERTS_AUT.B1_PER_ID2 = B.B1_PER_ID2
    AND GPROCESS_PROXIMITY_ALERTS_AUT.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted'
PRINT '-----------------------------------------';

PRINT 'DELETE FROM GPROCESS_NOTE'
PRINT '-----------------------------------------';
DELETE FROM GPROCESS_NOTE
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GPROCESS_NOTE.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GPROCESS_NOTE.B1_PER_ID1 = B.B1_PER_ID1
    AND GPROCESS_NOTE.B1_PER_ID2 = B.B1_PER_ID2
    AND GPROCESS_NOTE.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted'
PRINT '-----------------------------------------';

PRINT 'DELETE FROM GPROCESS_VALIDATION'
PRINT '-----------------------------------------';
DELETE FROM GPROCESS_VALIDATION
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GPROCESS_VALIDATION.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GPROCESS_VALIDATION.B1_PER_ID1 = B.B1_PER_ID1
    AND GPROCESS_VALIDATION.B1_PER_ID2 = B.B1_PER_ID2
    AND GPROCESS_VALIDATION.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted'
PRINT '-----------------------------------------';

PRINT 'DELETE FROM GPROCESS_HISTORY'
PRINT '-----------------------------------------';
DELETE FROM GPROCESS_HISTORY
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GPROCESS_HISTORY.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GPROCESS_HISTORY.B1_PER_ID1 = B.B1_PER_ID1
    AND GPROCESS_HISTORY.B1_PER_ID2 = B.B1_PER_ID2
    AND GPROCESS_HISTORY.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted'
PRINT '-----------------------------------------';

PRINT 'DELETE FROM GPROCESS_GROUP'
PRINT '-----------------------------------------';
DELETE FROM GPROCESS_GROUP
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GPROCESS_GROUP.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GPROCESS_GROUP.B1_PER_ID1 = B.B1_PER_ID1
    AND GPROCESS_GROUP.B1_PER_ID2 = B.B1_PER_ID2
    AND GPROCESS_GROUP.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted'
PRINT '-----------------------------------------';

PRINT '-----------------------------------------';
PRINT 'DELETE FROM GPROCESS'
DELETE FROM GPROCESS
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GPROCESS.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GPROCESS.B1_PER_ID1 = B.B1_PER_ID1
    AND GPROCESS.B1_PER_ID2 = B.B1_PER_ID2
    AND GPROCESS.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted'
PRINT '-----------------------------------------';

PRINT 'DELETE FROM GPROCESS_SPEC_INFO'
PRINT '-----------------------------------------';
DELETE FROM GPROCESS_SPEC_INFO
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GPROCESS_SPEC_INFO.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GPROCESS_SPEC_INFO.B1_PER_ID1 = B.B1_PER_ID1
    AND GPROCESS_SPEC_INFO.B1_PER_ID2 = B.B1_PER_ID2
    AND GPROCESS_SPEC_INFO.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted'
PRINT '-----------------------------------------';

PRINT 'DELETE FROM BACTIVITY_COMMENT'
PRINT '-----------------------------------------';
DELETE FROM BACTIVITY_COMMENT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE BACTIVITY_COMMENT.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND BACTIVITY_COMMENT.B1_PER_ID1 = B.B1_PER_ID1
    AND BACTIVITY_COMMENT.B1_PER_ID2 = B.B1_PER_ID2
    AND BACTIVITY_COMMENT.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM BATCH_INVFEE_HISTORY';
PRINT '-----------------------------------------';
DELETE FROM BATCH_INVFEE_HISTORY
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE BATCH_INVFEE_HISTORY.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND BATCH_INVFEE_HISTORY.B1_PER_ID1 = B.B1_PER_ID1
    AND BATCH_INVFEE_HISTORY.B1_PER_ID2 = B.B1_PER_ID2
    AND BATCH_INVFEE_HISTORY.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';


PRINT 'DELETE FROM BTIMEALERTCAPS';
PRINT '-----------------------------------------';
DELETE FROM BTIMEALERTCAPS
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE btimealertcaps.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND btimealertcaps.B1_PER_ID1 = B.B1_PER_ID1
    AND btimealertcaps.B1_PER_ID2 = B.B1_PER_ID2
    AND btimealertcaps.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM BATCH_INV_HISTORY';
PRINT '-----------------------------------------';
DELETE FROM BATCH_INV_HISTORY
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE BATCH_INV_HISTORY.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND BATCH_INV_HISTORY.B1_PER_ID1 = B.B1_PER_ID1
    AND BATCH_INV_HISTORY.B1_PER_ID2 = B.B1_PER_ID2
    AND BATCH_INV_HISTORY.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM BATCH_PERMIT_HISTORY';
PRINT '-----------------------------------------';
DELETE FROM BATCH_PERMIT_HISTORY
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE BATCH_PERMIT_HISTORY.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND BATCH_PERMIT_HISTORY.B1_PER_ID1 = B.B1_PER_ID1
    AND BATCH_PERMIT_HISTORY.B1_PER_ID2 = B.B1_PER_ID2
    AND BATCH_PERMIT_HISTORY.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM XDOCUMENT_ENTITY';
PRINT '-----------------------------------------';
DELETE FROM XDOCUMENT_ENTITY
WHERE EXISTS (
   SELECT '1' FROM #REMOVE_PER_LIST R, BDOCUMENT BD
   WHERE R.SERV_PROV_CODE = BD.SERV_PROV_CODE
    AND R.B1_PER_ID1 = BD.B1_PER_ID1
    AND R.B1_PER_ID2 = BD.B1_PER_ID2
    AND R.B1_PER_ID3 = BD.B1_PER_ID3
    AND BD.SERV_PROV_CODE = XDOCUMENT_ENTITY.SERV_PROV_CODE
    AND BD.DOC_SEQ_NBR = XDOCUMENT_ENTITY.DOC_SEQ_NBR
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM BDOCUMENT_CONTENT';
PRINT '-----------------------------------------';
DELETE FROM BDOCUMENT_CONTENT
WHERE EXISTS (
   SELECT '1' FROM #REMOVE_PER_LIST R, BDOCUMENT BD
   WHERE R.SERV_PROV_CODE = BD.SERV_PROV_CODE
    AND R.B1_PER_ID1 = BD.B1_PER_ID1
    AND R.B1_PER_ID2 = BD.B1_PER_ID2
    AND R.B1_PER_ID3 = BD.B1_PER_ID3
    AND BD.SERV_PROV_CODE = BDOCUMENT_CONTENT.SERV_PROV_CODE
    AND BD.DOC_SEQ_NBR = BDOCUMENT_CONTENT.DOC_SEQ_NBR
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM BDOCUMENT_COMMENT';
PRINT '-----------------------------------------';
DELETE FROM BDOCUMENT_COMMENT
WHERE EXISTS (
   SELECT '1' FROM #REMOVE_PER_LIST R, BDOCUMENT BD
   WHERE R.SERV_PROV_CODE = BD.SERV_PROV_CODE
    AND R.B1_PER_ID1 = BD.B1_PER_ID1
    AND R.B1_PER_ID2 = BD.B1_PER_ID2
    AND R.B1_PER_ID3 = BD.B1_PER_ID3
    AND BD.SERV_PROV_CODE = BDOCUMENT_COMMENT.SERV_PROV_CODE
    AND BD.DOC_SEQ_NBR = BDOCUMENT_COMMENT.DOC_SEQ_NBR
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM DOCUMENT_REVIEW_HISTORY';
PRINT '-----------------------------------------';
DELETE A FROM DOCUMENT_REVIEW_HISTORY A
 WHERE EXISTS 
      (SELECT SERV_PROV_CODE, 
              DOC_SEQ_NBR 
         FROM BDOCUMENT B
	    WHERE B.SERV_PROV_CODE = A.SERV_PROV_CODE
	      AND B.DOC_SEQ_NBR = A.DOC_SEQ_NBR
	      AND EXISTS
              (SELECT 1 FROM #REMOVE_PER_LIST C
                WHERE C.SERV_PROV_CODE = B.SERV_PROV_CODE
                  AND C.B1_PER_ID1 = B.B1_PER_ID1
                  AND C.B1_PER_ID2 = B.B1_PER_ID2
                  AND C.B1_PER_ID3 = B.B1_PER_ID3
              )
	   );
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM DOCUMENT_STATUS_HISTORY';
PRINT '-----------------------------------------';
DELETE A FROM DOCUMENT_STATUS_HISTORY A
 WHERE EXISTS 
      (SELECT SERV_PROV_CODE, 
              DOC_SEQ_NBR 
         FROM BDOCUMENT B
	    WHERE B.SERV_PROV_CODE = A.SERV_PROV_CODE
	      AND B.DOC_SEQ_NBR = A.DOC_SEQ_NBR
	      AND EXISTS
              (SELECT 1 FROM #REMOVE_PER_LIST C
                WHERE C.SERV_PROV_CODE = B.SERV_PROV_CODE
                  AND C.B1_PER_ID1 = B.B1_PER_ID1
                  AND C.B1_PER_ID2 = B.B1_PER_ID2
                  AND C.B1_PER_ID3 = B.B1_PER_ID3
              )
	   );
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM BDOCUMENT';
PRINT '-----------------------------------------';
DELETE FROM BDOCUMENT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE BDOCUMENT.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND BDOCUMENT.B1_PER_ID1 = B.B1_PER_ID1
    AND BDOCUMENT.B1_PER_ID2 = B.B1_PER_ID2
    AND BDOCUMENT.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM BSTRUCTURE';
PRINT '-----------------------------------------';
DELETE FROM BSTRUCTURE
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE BSTRUCTURE.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND BSTRUCTURE.B1_PER_ID1 = B.B1_PER_ID1
    AND BSTRUCTURE.B1_PER_ID2 = B.B1_PER_ID2
    AND BSTRUCTURE.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM BSTRUCTURE_ATTRIBUTE';
PRINT '-----------------------------------------';
DELETE FROM BSTRUCTURE_ATTRIBUTE
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE BSTRUCTURE_ATTRIBUTE.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND BSTRUCTURE_ATTRIBUTE.B1_PER_ID1 = B.B1_PER_ID1
    AND BSTRUCTURE_ATTRIBUTE.B1_PER_ID2 = B.B1_PER_ID2
    AND BSTRUCTURE_ATTRIBUTE.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM BSTRUCTURE_STRUCTURE';
PRINT '-----------------------------------------';
DELETE FROM BSTRUCTURE_STRUCTURE
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE BSTRUCTURE_STRUCTURE.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND BSTRUCTURE_STRUCTURE.B1_PER_ID1 = B.B1_PER_ID1
    AND BSTRUCTURE_STRUCTURE.B1_PER_ID2 = B.B1_PER_ID2
    AND BSTRUCTURE_STRUCTURE.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM I6COMMNT';
PRINT '-----------------------------------------';
DELETE FROM I6COMMNT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE I6COMMNT.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND I6COMMNT.B1_PER_ID1 = B.B1_PER_ID1
    AND I6COMMNT.B1_PER_ID2 = B.B1_PER_ID2
    AND I6COMMNT.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM C3CITATION';
PRINT '-----------------------------------------';
DELETE FROM C3CITATION
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE C3CITATION.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND C3CITATION.B1_PER_ID1 = B.B1_PER_ID1
    AND C3CITATION.B1_PER_ID2 = B.B1_PER_ID2
    AND C3CITATION.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM C3CITNCMNT';
PRINT '-----------------------------------------';
DELETE FROM C3CITNCMNT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE C3CITNCMNT.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND C3CITNCMNT.B1_PER_ID1 = B.B1_PER_ID1
    AND C3CITNCMNT.B1_PER_ID2 = B.B1_PER_ID2
    AND C3CITNCMNT.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM C3COMPLAINT';
PRINT '-----------------------------------------';
DELETE FROM C3COMPLAINT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE C3COMPLAINT.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND C3COMPLAINT.B1_PER_ID1 = B.B1_PER_ID1
    AND C3COMPLAINT.B1_PER_ID2 = B.B1_PER_ID2
    AND C3COMPLAINT.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM C3DEFENDANT';
PRINT '-----------------------------------------';
DELETE FROM C3DEFENDANT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE C3DEFENDANT.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND C3DEFENDANT.B1_PER_ID1 = B.B1_PER_ID1
    AND C3DEFENDANT.B1_PER_ID2 = B.B1_PER_ID2
    AND C3DEFENDANT.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM PHCALEND';
PRINT '-----------------------------------------';
DELETE FROM PHCALEND
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE PHCALEND.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND PHCALEND.B1_PER_ID1 = B.B1_PER_ID1
    AND PHCALEND.B1_PER_ID2 = B.B1_PER_ID2
    AND PHCALEND.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM GWORK_ORDER_COSTING';
PRINT '-----------------------------------------';
DELETE FROM GWORK_ORDER_COSTING
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GWORK_ORDER_COSTING.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GWORK_ORDER_COSTING.B1_PER_ID1 = B.B1_PER_ID1
    AND GWORK_ORDER_COSTING.B1_PER_ID2 = B.B1_PER_ID2
    AND GWORK_ORDER_COSTING.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM ACCOUNTING_AUDIT_TRAIL';
PRINT '-----------------------------------------';
DELETE FROM ACCOUNTING_AUDIT_TRAIL
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE ACCOUNTING_AUDIT_TRAIL.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND ACCOUNTING_AUDIT_TRAIL.B1_PER_ID1 = B.B1_PER_ID1
    AND ACCOUNTING_AUDIT_TRAIL.B1_PER_ID2 = B.B1_PER_ID2
    AND ACCOUNTING_AUDIT_TRAIL.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM GCOST_DISTRIBUTION_HISTORY';
PRINT '-----------------------------------------';
DELETE FROM GCOST_DISTRIBUTION_HISTORY
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GCOST_DISTRIBUTION_HISTORY.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GCOST_DISTRIBUTION_HISTORY.B1_PER_ID1 = B.B1_PER_ID1
    AND GCOST_DISTRIBUTION_HISTORY.B1_PER_ID2 = B.B1_PER_ID2
    AND GCOST_DISTRIBUTION_HISTORY.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM GCOST_DISTRIBUTION';
PRINT '-----------------------------------------';
DELETE FROM GCOST_DISTRIBUTION
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GCOST_DISTRIBUTION.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GCOST_DISTRIBUTION.B1_PER_ID1 = B.B1_PER_ID1
    AND GCOST_DISTRIBUTION.B1_PER_ID2 = B.B1_PER_ID2
    AND GCOST_DISTRIBUTION.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM SETDETAILS';
PRINT '-----------------------------------------';
DELETE FROM SETDETAILS
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE SETDETAILS.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND SETDETAILS.B1_PER_ID1 = B.B1_PER_ID1
    AND SETDETAILS.B1_PER_ID2 = B.B1_PER_ID2
    AND SETDETAILS.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM B3APO_ATTRIBUTE';
PRINT '-----------------------------------------';
DELETE FROM B3APO_ATTRIBUTE
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE B3APO_ATTRIBUTE.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND B3APO_ATTRIBUTE.B1_PER_ID1 = B.B1_PER_ID1
    AND B3APO_ATTRIBUTE.B1_PER_ID2 = B.B1_PER_ID2
    AND B3APO_ATTRIBUTE.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM BCALC_VALUATN'
PRINT '-----------------------------------------';
DELETE FROM BCALC_VALUATN
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE BCALC_VALUATN.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND BCALC_VALUATN.B1_PER_ID1 = B.B1_PER_ID1
    AND BCALC_VALUATN.B1_PER_ID2 = B.B1_PER_ID2
    AND BCALC_VALUATN.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM BAPPSPECTABLE_VALUE';
PRINT '-----------------------------------------';
DELETE FROM BAPPSPECTABLE_VALUE
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE BAPPSPECTABLE_VALUE.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND BAPPSPECTABLE_VALUE.B1_PER_ID1 = B.B1_PER_ID1
    AND BAPPSPECTABLE_VALUE.B1_PER_ID2 = B.B1_PER_ID2
    AND BAPPSPECTABLE_VALUE.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM BAPPSPECTABLE';
PRINT '-----------------------------------------';
DELETE FROM BAPPSPECTABLE
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE BAPPSPECTABLE.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND BAPPSPECTABLE.B1_PER_ID1 = B.B1_PER_ID1
    AND BAPPSPECTABLE.B1_PER_ID2 = B.B1_PER_ID2
    AND BAPPSPECTABLE.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM BCHCKBOX';
PRINT '-----------------------------------------';
DELETE FROM BCHCKBOX
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE BCHCKBOX.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND BCHCKBOX.B1_PER_ID1 = B.B1_PER_ID1
    AND BCHCKBOX.B1_PER_ID2 = B.B1_PER_ID2
    AND BCHCKBOX.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM B3CONTACT_ATTRIBUTE';
PRINT '-----------------------------------------';
DELETE FROM B3CONTACT_ATTRIBUTE
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE B3CONTACT_ATTRIBUTE.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND B3CONTACT_ATTRIBUTE.B1_PER_ID1 = B.B1_PER_ID1
    AND B3CONTACT_ATTRIBUTE.B1_PER_ID2 = B.B1_PER_ID2
    AND B3CONTACT_ATTRIBUTE.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM BVALUATN';
PRINT '-----------------------------------------';
DELETE FROM BVALUATN
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE BVALUATN.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND BVALUATN.B1_PER_ID1 = B.B1_PER_ID1
    AND BVALUATN.B1_PER_ID2 = B.B1_PER_ID2
    AND BVALUATN.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

--YBARGHOUTH 1/25/2022
PRINT 'DELETE FROM B6CONDIT_HISTORY_DETAIL';
PRINT '-----------------------------------------';
DELETE FROM B6CONDIT_HISTORY_DETAIL 
WHERE SERV_PROV_CODE = 'SCMN'
AND EXISTS (
	SELECT 1 FROM #REMOVE_PER_LIST R, B6CONDIT P1, B6CONDIT_HISTORY H
	WHERE R.SERV_PROV_CODE = P1.SERV_PROV_CODE
	AND B6CONDIT_HISTORY_DETAIL.B1_CON_HISTORY_NBR = H.B1_CON_HISTORY_NBR
	AND R.B1_PER_ID1 = P1.B1_PER_ID1
    AND R.B1_PER_ID2 = P1.B1_PER_ID2
    AND R.B1_PER_ID3 = P1.B1_PER_ID3
    AND P1.SERV_PROV_CODE = H.SERV_PROV_CODE
    AND P1.B1_CON_NBR = H.B1_CON_NBR
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM B6CONDIT_HISTORY';
PRINT '-----------------------------------------';
DELETE FROM B6CONDIT_HISTORY  
WHERE EXISTS (
   SELECT '1' FROM #REMOVE_PER_LIST R, B6CONDIT P1
   WHERE R.SERV_PROV_CODE = P1.SERV_PROV_CODE
    AND R.B1_PER_ID1 = P1.B1_PER_ID1
    AND R.B1_PER_ID2 = P1.B1_PER_ID2
    AND R.B1_PER_ID3 = P1.B1_PER_ID3
    AND P1.SERV_PROV_CODE = B6CONDIT_HISTORY.SERV_PROV_CODE
    AND P1.B1_CON_NBR = B6CONDIT_HISTORY.B1_CON_NBR
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM B6CONDIT';
PRINT '-----------------------------------------';
DELETE FROM B6CONDIT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE B6CONDIT.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND B6CONDIT.B1_PER_ID1 = B.B1_PER_ID1
    AND B6CONDIT.B1_PER_ID2 = B.B1_PER_ID2
    AND B6CONDIT.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM B3CONTRA';
PRINT '-----------------------------------------';
DELETE FROM B3CONTRA
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE B3CONTRA.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND B3CONTRA.B1_PER_ID1 = B.B1_PER_ID1
    AND B3CONTRA.B1_PER_ID2 = B.B1_PER_ID2
    AND B3CONTRA.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted'
PRINT '-----------------------------------------';
-- YBARGHOUTH 1/25/2022;
PRINT 'DELETE FROM G7CONTACT_ADDRESS (CAP_CONTACT addresses)';
PRINT '-----------------------------------------';

DELETE FROM G7CONTACT_ADDRESS 
WHERE G7CONTACT_ADDRESS.serv_prov_code = 'SCMN'
AND EXISTS( SELECT 1 FROM #REMOVE_PER_LIST B inner join B3CONTACT B3 ON
	b.SERV_PROV_CODE = G7CONTACT_ADDRESS.serv_prov_code
	AND b.SERV_PROV_CODE = B3.SERV_PROV_CODE
	AND b.B1_PER_ID1 = B3.B1_PER_ID1
	AND b.B1_PER_ID2 = B3.B1_PER_ID2
	AND b.B1_PER_ID3 = B3.B1_PER_ID3
	AND G7CONTACT_ADDRESS.G7_ENTITY_TYPE = 'CAP_CONTACT'
	AND B3.B1_CONTACT_NBR = G7CONTACT_ADDRESS.G7_ENTITY_ID
)
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted'
PRINT '-----------------------------------------';

PRINT 'DELETE FROM B3CONTACT';
PRINT '-----------------------------------------';
DELETE FROM B3CONTACT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE B3CONTACT.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND B3CONTACT.B1_PER_ID1 = B.B1_PER_ID1
    AND B3CONTACT.B1_PER_ID2 = B.B1_PER_ID2
    AND B3CONTACT.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

--YBARGHOUTH 1/25/2022
PRINT 'DELETE (orphaned/b3contact) FROM G7CONTACT_ADDRESS';
PRINT '-----------------------------------------';
DELETE FROM G7CONTACT_ADDRESS
where  serv_prov_code = 'SCMN'
and g7_entity_type = 'CAP_CONTACT'   
and not exists (
	select 1 from b3contact  b
	where G7CONTACT_ADDRESS.serv_prov_code = b.serv_prov_code
	and G7CONTACT_ADDRESS.g7_entity_type = 'CAP_CONTACT'
	and G7CONTACT_ADDRESS.G7_ENTITY_id = b.b1_contact_nbr
) 
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

--YBARGHOUTH 1/25/2022
PRINT 'DELETE (orphaned/G3contact) FROM G7CONTACT_ADDRESS';
PRINT '-----------------------------------------';
DELETE FROM G7CONTACT_ADDRESS
where  serv_prov_code = 'SCMN'
and g7_entity_type = 'CONTACT'   
and not exists (
	select 1 from G3contact  b
	where G7CONTACT_ADDRESS.serv_prov_code = b.serv_prov_code
	and G7CONTACT_ADDRESS.g7_entity_type = 'CONTACT'
	and G7CONTACT_ADDRESS.G7_ENTITY_id = b.G1_CONTACT_NBR
) 
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

--YBARGHOUTH 1/25/2022
PRINT 'DELETE FROM GTMPL_TABLE_VALUE (entity_type=37)'
PRINT '-----------------------------------------';
DELETE FROM GTMPL_TABLE_VALUE
where serv_prov_code = 'SCMN' 
and entity_type = 37
and not exists (
	select 1 from b3contact b
	where GTMPL_TABLE_VALUE.serv_prov_code = b.serv_prov_code
	and GTMPL_TABLE_VALUE.entity_type = 37
	and b.b1_contact_nbr = GTMPL_TABLE_VALUE.entity_seq1 
)
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

--YBARGHOUTH 1/25/2022
PRINT 'DELETE FROM GTMPL_TABLE_VALUE (entity_type=38)';
PRINT '-----------------------------------------';
DELETE FROM GTMPL_TABLE_VALUE
where serv_prov_code = 'SCMN' 
and entity_type = 38
and not exists (
	select 1 from b3contact b
	where GTMPL_TABLE_VALUE.serv_prov_code = b.serv_prov_code
	and GTMPL_TABLE_VALUE.entity_type = 38
	and b.b1_contact_nbr = GTMPL_TABLE_VALUE.entity_seq1 
)
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

--YBARGHOUTH 1/25/2022
PRINT 'DELETE FROM GTMPL_ATTRIBUTE (TEMPLATE_TYPE=1, entity_type=37)';
PRINT '-----------------------------------------';
DELETE FROM GTMPL_ATTRIBUTE
where serv_prov_code = 'SCMN' 
and entity_type = 37
AND TEMPLATE_TYPE = 1
and not exists (
	select 1 from b3contact b
	where GTMPL_ATTRIBUTE.serv_prov_code = b.serv_prov_code
	and GTMPL_ATTRIBUTE.entity_type = 37
	and b.b1_contact_nbr = GTMPL_ATTRIBUTE.entity_seq1 
	AND GTMPL_ATTRIBUTE.TEMPLATE_TYPE = 1
)
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';
--YBARGHOUTH 1/25/2022

PRINT 'DELETE FROM GTMPL_ATTRIBUTE (TEMPLATE_TYPE=1, entity_type=38)';
PRINT '-----------------------------------------';
DELETE FROM GTMPL_ATTRIBUTE
where serv_prov_code = 'SCMN' 
and entity_type = 38
AND TEMPLATE_TYPE = 1
and not exists (
	select 1 from b3contact b
	where GTMPL_ATTRIBUTE.serv_prov_code = b.serv_prov_code
	and GTMPL_ATTRIBUTE.entity_type = 38
	and b.b1_contact_nbr = GTMPL_ATTRIBUTE.entity_seq1 
	AND GTMPL_ATTRIBUTE.TEMPLATE_TYPE = 1
)
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

--YBARGHOUTH 1/25/2022
PRINT 'DELETE FROM GTMPL_ATTRIBUTE (TEMPLATE_TYPE=2, entity_type=37)';
DELETE FROM GTMPL_ATTRIBUTE
where serv_prov_code = 'SCMN' 
and entity_type = 37
AND TEMPLATE_TYPE = 2
and not exists (
	select 1 from b3contact b
	where GTMPL_ATTRIBUTE.serv_prov_code = b.serv_prov_code
	and GTMPL_ATTRIBUTE.entity_type = 37
	and b.b1_contact_nbr = GTMPL_ATTRIBUTE.entity_seq1 
	AND GTMPL_ATTRIBUTE.TEMPLATE_TYPE = 2
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

--YBARGHOUTH 1/25/2022
PRINT 'DELETE FROM GTMPL_ATTRIBUTE (TEMPLATE_TYPE=2, entity_type=38)';
PRINT '-----------------------------------------';
DELETE FROM GTMPL_ATTRIBUTE
where serv_prov_code = 'SCMN' 
and entity_type = 38
AND TEMPLATE_TYPE = 2
and not exists (
	select 1 from b3contact b
	where GTMPL_ATTRIBUTE.serv_prov_code = b.serv_prov_code
	and GTMPL_ATTRIBUTE.entity_type = 38
	and b.b1_contact_nbr = GTMPL_ATTRIBUTE.entity_seq1 
	AND GTMPL_ATTRIBUTE.TEMPLATE_TYPE = 2
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

--YBARGHOUTH 1/25/2022
PRINT 'DELETE (orphaned g3contact) FROM GTMPL_TABLE_VALUE (entity_type=37)';
PRINT '-----------------------------------------';
DELETE from GTMPL_TABLE_VALUE 
where serv_prov_code = 'SCMN'
and entity_type = 37
and not exists (
	select 1 from g3contact b
	where GTMPL_TABLE_VALUE.serv_prov_code = b.serv_prov_code
	and GTMPL_TABLE_VALUE.entity_type = 37
	and b.g1_contact_nbr = GTMPL_TABLE_VALUE.entity_seq1
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

--YBARGHOUTH 1/25/2022
PRINT 'DELETE (orphaned g3contact) FROM GTMPL_TABLE_VALUE (entity_type=38)';
PRINT '-----------------------------------------';
DELETE from GTMPL_TABLE_VALUE 
where serv_prov_code = 'SCMN'
and entity_type = 38
and not exists (
	select 1 from g3contact b
	where GTMPL_TABLE_VALUE.serv_prov_code = b.serv_prov_code
	and GTMPL_TABLE_VALUE.entity_type = 38
	and b.g1_contact_nbr = GTMPL_TABLE_VALUE.entity_seq1
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

--YBARGHOUTH 1/25/2022
PRINT 'DELETE (orphaned g3contact) FROM GTMPL_ATTRIBUTE (TEMPLATE_TYPE=1, entity_type=37)';
PRINT '-----------------------------------------';
DELETE FROM GTMPL_ATTRIBUTE
where serv_prov_code = 'SCMN' 
and entity_type = 37
AND TEMPLATE_TYPE = 1
and not exists (
	select 1 from g3contact b
	where GTMPL_ATTRIBUTE.serv_prov_code = b.serv_prov_code
	and GTMPL_ATTRIBUTE.entity_type = 37
	and b.g1_contact_nbr = GTMPL_ATTRIBUTE.entity_seq1 
	AND GTMPL_ATTRIBUTE.TEMPLATE_TYPE = 1
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

--YBARGHOUTH 1/25/2022
PRINT 'DELETE (orphaned g3contact) FROM GTMPL_ATTRIBUTE (TEMPLATE_TYPE=1, entity_type=38)';
PRINT '-----------------------------------------';
DELETE FROM GTMPL_ATTRIBUTE
where serv_prov_code = 'SCMN' 
and entity_type = 38
AND TEMPLATE_TYPE = 1
and not exists (
	select 1 from g3contact b
	where GTMPL_ATTRIBUTE.serv_prov_code = b.serv_prov_code
	and GTMPL_ATTRIBUTE.entity_type = 38
	and b.g1_contact_nbr = GTMPL_ATTRIBUTE.entity_seq1 
	AND GTMPL_ATTRIBUTE.TEMPLATE_TYPE = 1
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

--YBARGHOUTH 1/25/2022
PRINT 'DELETE (orphaned g3contact) FROM GTMPL_ATTRIBUTE (TEMPLATE_TYPE=2, entity_type=37)';
PRINT '-----------------------------------------';
DELETE FROM GTMPL_ATTRIBUTE
where serv_prov_code = 'SCMN' 
and entity_type = 37
AND TEMPLATE_TYPE = 2
and not exists (
	select 1 from g3contact b
	where GTMPL_ATTRIBUTE.serv_prov_code = b.serv_prov_code
	and GTMPL_ATTRIBUTE.entity_type = 37
	and b.g1_contact_nbr = GTMPL_ATTRIBUTE.entity_seq1 
	AND GTMPL_ATTRIBUTE.TEMPLATE_TYPE = 2
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

--YBARGHOUTH 1/25/2022
PRINT 'DELETE (orphaned g3contact) FROM GTMPL_ATTRIBUTE (TEMPLATE_TYPE=2, entity_type=38)';
PRINT '-----------------------------------------';
DELETE FROM GTMPL_ATTRIBUTE
where serv_prov_code = 'SCMN' 
and entity_type = 38
AND TEMPLATE_TYPE = 2
and not exists (
	select 1 from g3contact b
	where GTMPL_ATTRIBUTE.serv_prov_code = b.serv_prov_code
	and GTMPL_ATTRIBUTE.entity_type = 38
	and b.g1_contact_nbr = GTMPL_ATTRIBUTE.entity_seq1 
	AND GTMPL_ATTRIBUTE.TEMPLATE_TYPE = 2
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM F4FEEITEM_AUDIT_TRAIL';
PRINT '-----------------------------------------';
DELETE FROM F4FEEITEM_AUDIT_TRAIL
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE F4FEEITEM_AUDIT_TRAIL.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND F4FEEITEM_AUDIT_TRAIL.B1_PER_ID1 = B.B1_PER_ID1
    AND F4FEEITEM_AUDIT_TRAIL.B1_PER_ID2 = B.B1_PER_ID2
    AND F4FEEITEM_AUDIT_TRAIL.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM X4PAYMENT_FEEITEM';
PRINT '-----------------------------------------';
DELETE FROM X4PAYMENT_FEEITEM
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE X4PAYMENT_FEEITEM.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND X4PAYMENT_FEEITEM.B1_PER_ID1 = B.B1_PER_ID1
    AND X4PAYMENT_FEEITEM.B1_PER_ID2 = B.B1_PER_ID2
    AND X4PAYMENT_FEEITEM.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM X4PAYMENT_INVOICE';
PRINT '-----------------------------------------';
DELETE FROM X4PAYMENT_INVOICE
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST_INVOICE B
  WHERE X4PAYMENT_INVOICE.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND X4PAYMENT_INVOICE.INVOICE_NBR = B.INVOICE_NBR
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM X4FEEITEM_INVOICE'
PRINT '-----------------------------------------';
DELETE FROM X4FEEITEM_INVOICE
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE X4FEEITEM_INVOICE.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND X4FEEITEM_INVOICE.B1_PER_ID1 = B.B1_PER_ID1
    AND X4FEEITEM_INVOICE.B1_PER_ID2 = B.B1_PER_ID2
    AND X4FEEITEM_INVOICE.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

------------------------------------------------------------------------------------------------------
--Special handle: DELETE FROM f4acct_transaction and f4pos_transaction if it has no child data (begin)
------------------------------------------------------------------------------------------------------
PRINT 'DELETE FROM F4ACCT_TRANSACTION';
PRINT '-----------------------------------------';
DELETE FROM F4ACCT_TRANSACTION
WHERE EXISTS
( SELECT 1 FROM F4PAYMENT B, #REMOVE_PER_LIST C
  WHERE F4ACCT_TRANSACTION.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND F4ACCT_TRANSACTION.PAYMENT_SEQ_NBR = B.PAYMENT_SEQ_NBR
	AND C.SERV_PROV_CODE=B.SERV_PROV_CODE
	AND C.B1_PER_ID1 = B.B1_PER_ID1
    AND C.B1_PER_ID2 = B.B1_PER_ID2
    AND C.B1_PER_ID3 = B.B1_PER_ID3 
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM F4POS_TRANSACTION';
PRINT '-----------------------------------------';
DELETE FROM F4POS_TRANSACTION
WHERE EXISTS
( SELECT 1 FROM F4FEEITEM B, #REMOVE_PER_LIST C
  WHERE F4POS_TRANSACTION.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND F4POS_TRANSACTION.POS_TRANS_SEQ = B.POS_TRANS_SEQ
	AND C.SERV_PROV_CODE=B.SERV_PROV_CODE
	AND C.B1_PER_ID1 = B.B1_PER_ID1
    AND C.B1_PER_ID2 = B.B1_PER_ID2
    AND C.B1_PER_ID3 = B.B1_PER_ID3 
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

------------------------------------------------------------------------------------------------------
--Special handle: DELETE FROM f4acct_transaction and f4pos_transaction if it has no child data (end)
------------------------------------------------------------------------------------------------------

PRINT 'DELETE FROM F4PAYMENT';
PRINT '-----------------------------------------';
DELETE FROM F4PAYMENT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE F4PAYMENT.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND F4PAYMENT.B1_PER_ID1 = B.B1_PER_ID1
    AND F4PAYMENT.B1_PER_ID2 = B.B1_PER_ID2
    AND F4PAYMENT.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM F4RECEIPT';
PRINT '-----------------------------------------';
DELETE FROM F4RECEIPT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST_RECEIPT B
  WHERE F4RECEIPT.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND F4RECEIPT.RECEIPT_NBR = B.RECEIPT_NBR
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM F4INVOICE';
PRINT '-----------------------------------------';
DELETE FROM F4INVOICE
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST_INVOICE B
  WHERE F4INVOICE.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND F4INVOICE.INVOICE_NBR = B.INVOICE_NBR
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM F4FEEITEM';
PRINT '-----------------------------------------';
DELETE FROM F4FEEITEM
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE F4FEEITEM.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND F4FEEITEM.B1_PER_ID1 = B.B1_PER_ID1
    AND F4FEEITEM.B1_PER_ID2 = B.B1_PER_ID2
    AND F4FEEITEM.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM B3OWNERS';
PRINT '-----------------------------------------';
DELETE FROM B3OWNERS
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE B3OWNERS.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND B3OWNERS.B1_PER_ID1 = B.B1_PER_ID1
    AND B3OWNERS.B1_PER_ID2 = B.B1_PER_ID2
    AND B3OWNERS.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM B3PARCEL';
PRINT '-----------------------------------------';
DELETE FROM B3PARCEL
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE B3PARCEL.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND B3PARCEL.B1_PER_ID1 = B.B1_PER_ID1
    AND B3PARCEL.B1_PER_ID2 = B.B1_PER_ID2
    AND B3PARCEL.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM BWORKDES';
PRINT '-----------------------------------------';
DELETE FROM BWORKDES
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE BWORKDES.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND BWORKDES.B1_PER_ID1 = B.B1_PER_ID1
    AND BWORKDES.B1_PER_ID2 = B.B1_PER_ID2
    AND BWORKDES.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM B3ADDRES';
PRINT '-----------------------------------------';
DELETE FROM B3ADDRES
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE B3ADDRES.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND B3ADDRES.B1_PER_ID1 = B.B1_PER_ID1
    AND B3ADDRES.B1_PER_ID2 = B.B1_PER_ID2
    AND B3ADDRES.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM G6PERMIT';
PRINT '-----------------------------------------';
DELETE FROM G6PERMIT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE G6PERMIT.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND G6PERMIT.B1_PER_ID1 = B.B1_PER_ID1
    AND G6PERMIT.B1_PER_ID2 = B.B1_PER_ID2
    AND G6PERMIT.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM G6GUIDESHEET';
PRINT '-----------------------------------------';
DELETE FROM G6GUIDESHEET
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE G6GUIDESHEET.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND G6GUIDESHEET.B1_PER_ID1 = B.B1_PER_ID1
    AND G6GUIDESHEET.B1_PER_ID2 = B.B1_PER_ID2
    AND G6GUIDESHEET.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM G6GUIDETEXT';
PRINT '-----------------------------------------';
DELETE FROM G6GUIDETEXT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE G6GUIDETEXT.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND G6GUIDETEXT.B1_PER_ID1 = B.B1_PER_ID1
    AND G6GUIDETEXT.B1_PER_ID2 = B.B1_PER_ID2
    AND G6GUIDETEXT.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM G6ISSFLG';
PRINT '-----------------------------------------';
DELETE FROM G6ISSFLG
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE G6ISSFLG.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND G6ISSFLG.B1_PER_ID1 = B.B1_PER_ID1
    AND G6ISSFLG.B1_PER_ID2 = B.B1_PER_ID2
    AND G6ISSFLG.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM G6COMMNT';
PRINT '-----------------------------------------';
DELETE FROM G6COMMNT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE G6COMMNT.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND G6COMMNT.B1_PER_ID1 = B.B1_PER_ID1
    AND G6COMMNT.B1_PER_ID2 = B.B1_PER_ID2
    AND G6COMMNT.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM XG6ACTION';
PRINT '-----------------------------------------';
DELETE FROM XG6ACTION
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE XG6ACTION.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND XG6ACTION.B1_PER_ID1 = B.B1_PER_ID1
    AND XG6ACTION.B1_PER_ID2 = B.B1_PER_ID2
    AND XG6ACTION.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM G6ACTION';
PRINT '-----------------------------------------';
DELETE FROM G6ACTION
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE G6ACTION.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND G6ACTION.B1_PER_ID1 = B.B1_PER_ID1
    AND G6ACTION.B1_PER_ID2 = B.B1_PER_ID2
    AND G6ACTION.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM BPERMIT_ACTIVITY_LOG';
PRINT '-----------------------------------------';
DELETE FROM BPERMIT_ACTIVITY_LOG
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE BPERMIT_ACTIVITY_LOG.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND BPERMIT_ACTIVITY_LOG.B1_PER_ID1 = B.B1_PER_ID1
    AND BPERMIT_ACTIVITY_LOG.B1_PER_ID2 = B.B1_PER_ID2
    AND BPERMIT_ACTIVITY_LOG.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM BPERMIT_COMMENT';
PRINT '-----------------------------------------';
DELETE FROM BPERMIT_COMMENT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE BPERMIT_COMMENT.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND BPERMIT_COMMENT.B1_PER_ID1 = B.B1_PER_ID1
    AND BPERMIT_COMMENT.B1_PER_ID2 = B.B1_PER_ID2
    AND BPERMIT_COMMENT.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM BPERMIT_DETAIL';
PRINT '-----------------------------------------';
DELETE FROM BPERMIT_DETAIL
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE BPERMIT_DETAIL.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND BPERMIT_DETAIL.B1_PER_ID1 = B.B1_PER_ID1
    AND BPERMIT_DETAIL.B1_PER_ID2 = B.B1_PER_ID2
    AND BPERMIT_DETAIL.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM XACCT_PERMIT';
PRINT '-----------------------------------------';
DELETE FROM XACCT_PERMIT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE XACCT_PERMIT.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND XACCT_PERMIT.B1_PER_ID1 = B.B1_PER_ID1
    AND XACCT_PERMIT.B1_PER_ID2 = B.B1_PER_ID2
    AND XACCT_PERMIT.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM XGCALENDAR_RESOURCES';
PRINT '-----------------------------------------';
DELETE FROM XGCALENDAR_RESOURCES
WHERE EXISTS
(SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE XGCALENDAR_RESOURCES.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND XGCALENDAR_RESOURCES.RESOURCE_ID1 = B.b1_per_id1+'-'+B.B1_pER_ID2+'-'+B.B1_PER_ID3);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM GCALENDAR_DETAIL';
PRINT '-----------------------------------------';
DELETE FROM GCALENDAR_DETAIL
WHERE EXISTS
(SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE GCALENDAR_DETAIL.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND GCALENDAR_DETAIL.ALT_ID = B.B1_ALT_ID);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

--add by cindy 11/15
PRINT 'DELETE FROM XRECORD_CONTACT_ENTITY';
PRINT '-----------------------------------------';
DELETE FROM XRECORD_CONTACT_ENTITY
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE XRECORD_CONTACT_ENTITY.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND XRECORD_CONTACT_ENTITY.B1_PER_ID1 = B.B1_PER_ID1
    AND XRECORD_CONTACT_ENTITY.B1_PER_ID2 = B.B1_PER_ID2
    AND XRECORD_CONTACT_ENTITY.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM G7SERIES_UPDATE_LOG'
PRINT '-----------------------------------------';
DELETE FROM G7SERIES_UPDATE_LOG WHERE SERV_PROV_CODE='SCMN' AND 
	((G7_UPDATE_VALUE='LIC_PROF' AND EXISTS (SELECT 1 FROM XMEETING_ATTENDEE_ENTITY WHERE SERV_PROV_CODE=G7SERIES_UPDATE_LOG.SERV_PROV_CODE AND G7SERIES_UPDATE_LOG.G7_UPDATE_ID=MEETING_ID 
		AND G7SERIES_UPDATE_LOG.G7_UPDATE_VALUE2=ENTITY_VALUE)) 
		OR (G7_UPDATE_VALUE='CONTACT' AND EXISTS (SELECT 1 FROM XMEETING_ATTENDEE_ENTITY 
			WHERE G7SERIES_UPDATE_LOG.SERV_PROV_CODE= SERV_PROV_CODE AND G7SERIES_UPDATE_LOG.G7_UPDATE_ID=MEETING_ID 
			AND G7SERIES_UPDATE_LOG.G7_UPDATE_VALUE2=ENTITY_VALUE)) OR (G7_UPDATE_VALUE='USER' 
				AND EXISTS (SELECT 1 FROM XMEETING_ATTENDEE_ENTITY WHERE G7SERIES_UPDATE_LOG.SERV_PROV_CODE= SERV_PROV_CODE 
						AND G7SERIES_UPDATE_LOG.G7_UPDATE_ID=MEETING_ID AND G7SERIES_UPDATE_LOG.G7_UPDATE_VALUE2=ENTITY_VALUE)));
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM GAUDIT_HISTORY'
PRINT '-----------------------------------------';
DELETE FROM GAUDIT_HISTORY WHERE SERV_PROV_CODE='SCMN' AND ENTITY_TYPE IN ('0','1','2','3','4','9','10','11','12','13','15','16','17','18','19','20','21','22','23')
                  and ENTITY_ID IN (SELECT B1_pER_ID1+'-'+B1_PER_ID2+'-'+B1_PER_ID3 FROM #REMOVE_PER_LIST);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM GCONT_EDU'
PRINT '-----------------------------------------';
DELETE FROM GCONT_EDU WHERE SERV_PROV_CODE='SCMN' AND ENT_TYPE='CAP_CONTEDU' 
		AND EXISTS( SELECT 1 FROM B1PERMIT WHERE SERV_PROV_CODE=GCONT_EDU.SERV_PROV_CODE AND B1_PER_ID1=GCONT_EDU.B1_PER_ID1 AND B1_PER_ID2=GCONT_EDU.B1_PER_ID2 AND B1_PER_ID3=GCONT_EDU.B1_PER_ID3);

PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'DELETE FROM GEDUCATION';
PRINT '-----------------------------------------';
DELETE FROM GEDUCATION WHERE SERV_PROV_CODE='SCMN' AND ENT_TYPE='CAP_EDU' 
		AND EXISTS( SELECT 1 FROM B1PERMIT WHERE SERV_PROV_CODE=GEDUCATION.SERV_PROV_CODE AND B1_PER_ID1=GEDUCATION.B1_PER_ID1 AND B1_PER_ID2=GEDUCATION.B1_PER_ID2 AND B1_PER_ID3=GEDUCATION.B1_PER_ID3);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';

PRINT 'DELETE FROM GEXAM';
PRINT '-----------------------------------------';
DELETE FROM GEXAM WHERE SERV_PROV_CODE='SCMN' AND ENT_TYPE='CAP_EXAM' 
	AND EXISTS( SELECT 1 FROM B1PERMIT WHERE SERV_PROV_CODE=GEXAM.SERV_PROV_CODE AND B1_PER_ID1=GEXAM.B1_PER_ID1 AND B1_PER_ID2=GEXAM.B1_PER_ID2 AND B1_PER_ID3=GEXAM.B1_PER_ID3);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';

PRINT 'DELETE FROM B1PERMIT';
PRINT '-----------------------------------------';
DELETE FROM B1PERMIT
WHERE EXISTS
( SELECT 1 FROM #REMOVE_PER_LIST B
  WHERE B1PERMIT.SERV_PROV_CODE = B.SERV_PROV_CODE
    AND B1PERMIT.B1_PER_ID1 = B.B1_PER_ID1
    AND B1PERMIT.B1_PER_ID2 = B.B1_PER_ID2
    AND B1PERMIT.B1_PER_ID3 = B.B1_PER_ID3
);
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

--YBARGHOUTH 1/25/2022
PRINT 'DELETE (orphaned) FROM XRECORD_CONTACT_ENTITY';
PRINT '-----------------------------------------';
DELETE FROM XRECORD_CONTACT_ENTITY WHERE 
SERV_PROV_CODE='SCMN'
AND NOT EXISTS(
SELECT 1 FROM B1PERMIT B WHERE 
	B.SERV_PROV_CODE = XRECORD_CONTACT_ENTITY.SERV_PROV_CODE
    AND XRECORD_CONTACT_ENTITY.B1_PER_ID1 = B.B1_PER_ID1
    AND XRECORD_CONTACT_ENTITY.B1_PER_ID2 = B.B1_PER_ID2
    AND XRECORD_CONTACT_ENTITY.B1_PER_ID3 = B.B1_PER_ID3
)
PRINT FORMAT(@@ROWCOUNT,'N0') + ' row(s) deleted';
PRINT '-----------------------------------------';

PRINT 'Remove Trust Accounts and Detail;
PRINT '-----------------------------------------';

--DECLARE @SPC VARCHAR(30) = 'SCMN';
--DECLARE @PREDICATE varchar(max) = 'SERV_PROV_CODE = ''SCMN''';
--DECLARE @sql nvarchar(max)
--PRINT @PREDICATE;

-- Delete Trust Account Detail Transactions F4ACCT_TRANSACTION
SET @sql = N'delete from F4ACCT_TRANSACTION WHERE ' + @PREDICATE;
PRINT @SQL;
EXEC sp_executesql @sql;
 
-- Delete Trust Account Header Records 
SET @sql = N'delete from RACCOUNT WHERE ' + @PREDICATE;
PRINT @SQL;
EXEC sp_executesql @sql;

