IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.SEQUENCES WHERE SEQUENCE_NAME = N'DOG_NUM')
BEGIN
	DROP SEQUENCE DOG_NUM
END
go

CREATE SEQUENCE DOG_NUM
    AS int  
	START WITH 1
    INCREMENT BY 1;
go

update [AAA_Dog_License] 
set accelaid = FORMAT(NEXT VALUE FOR DOG_NUM, 'HDOG24-0000')
