/*
SCRIPT: 02_CREATE_VIEWS.SQL
AUTHOR: DANE QUATACKER, ACCELA INC.
DATE: 11/22/2011
DESCRIPTION: CREATES BASE VIEWS FOR STANDARD MAP CONVERSION IN AN SQL SERVER DATABASE

UPDATES:
11/13/2012 - DQ - ADDED 7.2 FP2 UPDATES

*/
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_ACTIVITY')
BEGIN
DROP VIEW AASTD_PERMIT_ACTIVITY
END
go
CREATE VIEW AASTD_PERMIT_ACTIVITY AS
SELECT
  PERMITNUM,
  ACT_NAME,
  ACT_DES,
  ACT_TYPE,
  ACT_DATE,
  ACT_DEPT,
  ACT_STAF,
  REC_DATE,
  REC_FUL_NAM,
  INTERNAL_USE_ONLY,
  ACT_DUE_DATE,
  ACT_PRIORITY,
  ACT_STATUS,
  act_unique_id
FROM AATABLE_PERMIT_ACTIVITY
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_ACTIVITY_ASI')
BEGIN
DROP VIEW AASTD_PERMIT_ACTIVITY_ASI
END
go
CREATE VIEW AASTD_PERMIT_ACTIVITY_ASI AS
SELECT 
PERMITNUM,
act_unique_id,
asi_group_code, 
asi_sub_group ,
asi_field_label,
asi_field_value
FROM AATABLE_PERMIT_ACTIVITY_ASI
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_ADDRESS')
BEGIN
DROP VIEW AASTD_PERMIT_ADDRESS
END
go
CREATE VIEW AASTD_PERMIT_ADDRESS AS
SELECT
  PERMITNUM,
  ISPRIMARY,
  STR_NUM_START,
  STR_NUM_END,
  STR_FRAC_START,
  STR_FRAC_END,
  STR_DIR,
  STR_NAME,
  STR_SUFFIX,
  STR_SUFFIX_DIR,
  STR_PREFIX,
  STR_UNIT_START,
  STR_UNIT_END,
  STR_UNIT_TYPE,
  SITUS_CITY,
  SITUS_STATE,
  SITUS_ZIP,
  SITUS_COUNTY,
  SITUS_COUNTRY,
  SITUS_COUNTRY_CODE,
  X_COORD,
  Y_COORD,
  ADDR_DESC,
  FULL_ADDRESS,
  ADDRESS1,
  ADDRESS2,
  SITUS_NBRHD,
  EXT_ADDRESS_UID,
  STREET_NAME_START, -- Added by OMATKARI 8/19/18
  STREET_NAME_END, -- Added by OMATKARI 8/19/18
  CROSS_STREET_NAME_START, -- Added by OMATKARI 8/19/18
  CROSS_STREET_NAME_END, -- Added by OMATKARI 8/19/18
  HSE_NBR_ALPHA_START,	-- Added By ALTARAZI 04/09/19
  HSE_NBR_ALPHA_END,	-- Added By ALTARAZI 04/09/19
  LEVEL_PREFIX,			-- Added By ALTARAZI 04/09/19
  LEVEL_NBR_START,	-- Added By ALTARAZI 04/09/19
  LEVEL_NBR_END 		-- Added By ALTARAZI 04/09/19
FROM AATABLE_PERMIT_ADDRESS
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_ADDRESS_TYPE')
BEGIN
DROP VIEW AASTD_PERMIT_ADDRESS_TYPE
END
go
CREATE VIEW AASTD_PERMIT_ADDRESS_TYPE AS
SELECT
  PERMITNUM,
  FULL_ADDRESS,
  ADDRESS_TYPE
FROM AATABLE_PERMIT_ADDRESS_TYPE
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_ATTRIB')
BEGIN
DROP VIEW AASTD_PERMIT_ATTRIB
END
go
CREATE VIEW AASTD_PERMIT_ATTRIB AS
SELECT
  PERMITNUM,
  ATTRIB_TYPE,
  ATTRIB_TEMP_NAME,
  ATTRIB_NAME,
  ATTRIB_VALUE,
  ATTRIB_KEY
FROM AATABLE_PERMIT_ATTRIB
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_CALCVALUATN')
BEGIN
DROP VIEW AASTD_PERMIT_CALCVALUATN
END
go
CREATE VIEW AASTD_PERMIT_CALCVALUATN AS
SELECT
  PERMITNUM,
  OCC_TYPE,
  CONST_TYPE,
  UNIT_VALUE,
  AREA,
  TOTALVALUE,
  UNIT_TYPE,
  VALUATN_VERSION
FROM AATABLE_PERMIT_CALCVALUATN
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_COMMENT')
BEGIN
DROP VIEW AASTD_PERMIT_COMMENT
END
go
CREATE VIEW AASTD_PERMIT_COMMENT AS
SELECT
  PERMITNUM,
  COMMENTS,
  ADDEDBY,
  ADDEDDATE
FROM AATABLE_PERMIT_COMMENT
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_CONDITIONS')
BEGIN
DROP VIEW AASTD_PERMIT_CONDITIONS
END
go
CREATE VIEW AASTD_PERMIT_CONDITIONS AS
SELECT
  PERMITNUM,
  CON_COMMENTS,
  CON_DES,
  CON_IMPACT_CODE,
  EFFECTIVE_DATE,
  EXPIR_DATE,
  ISS_DD,
  STAT_DD,
  CON_STATUS,
  CON_TYPE,
  DISPLAY_ORDER,
  CON_INHERITABLE,
  CON_GROUP,
  ISS_USER_ID,
  STAT_USER_ID,
  INC_CON_NAME,
  INC_SHORT_DESC,
  DIS_CON_NOTICE,
  CON_STATUS_TYP,
  LONG_COMMENTS
FROM AATABLE_PERMIT_CONDITIONS
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_CONT_EDU')
BEGIN
DROP VIEW AASTD_PERMIT_CONT_EDU
END
go
CREATE VIEW AASTD_PERMIT_CONT_EDU AS
SELECT
  PERMITNUM,
  PROVIDER_NAME,
  CONT_EDU_NAME,
  IS_REQUIRED,
  EDU_CLASS,
  DATE_OF_CLASS,
  HOURS_COMPLETED,
  GRADING_STYLE,
  FINAL_SCORE,
  PASSING_SCORE,
  EDU_COMMENTS,
  ADDR1,
  ADDR2,
  ADDR3,
  CITY,
  STATE,
  ZIP,
  PH1_COUNTRY_CODE,
  PH1,
  PH2_COUNTRY_CODE,
  PH2,
  FAX_COUNTRY_CODE,
  FAX,
  EMAIL,
  B1_COUNTRY
FROM AATABLE_PERMIT_CONT_EDU
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_EDUCATION')
BEGIN
DROP VIEW AASTD_PERMIT_EDUCATION
END
go
CREATE VIEW AASTD_PERMIT_EDUCATION AS
SELECT
  PERMITNUM,
  PROVIDER_NAME,
  EDUCATION_NAME,
  EDU_DEGREE,
  YEAR_ATTENDED,
  YEAR_GRADUATED,
  EDU_COMMENTS,
  IS_REQUIRED,
  ADDR1,
  ADDR2,
  ADDR3,
  CITY,
  STATE,
  ZIP,
  PH1_COUNTRY_CODE,
  PH1,
  PH2_COUNTRY_CODE,
  PH2,
  FAX_COUNTRY_CODE,
  FAX,
  EMAIL,
  B1_COUNTRY
FROM AATABLE_PERMIT_EDUCATION
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_EXAM')
BEGIN
DROP VIEW AASTD_PERMIT_EXAM
END
go
CREATE VIEW AASTD_PERMIT_EXAM AS
SELECT
  PERMITNUM,
  PROVIDER_NAME,
  EXAM_NAME,
  IS_REQUIRED,
  EXAM_DATE,
  GRADING_STYLE,
  FINAL_SCORE,
  PASSING_SCORE,
  EXAM_COMMENTS,
  ADDR1,
  ADDR2,
  ADDR3,
  CITY,
  STATE,
  ZIP,
  PH1_COUNTRY_CODE,
  PH1,
  PH2_COUNTRY_CODE,
  PH2,
  FAX_COUNTRY_CODE,
  FAX,
  EMAIL,
  B1_COUNTRY
FROM AATABLE_PERMIT_EXAM
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_FEE')
BEGIN
DROP VIEW AASTD_PERMIT_FEE
END
go
CREATE VIEW AASTD_PERMIT_FEE AS
SELECT
  PERMITNUM,
  FEE_KEY,
  GF_FEE_PERIOD,
  FEE_ITEM_AMOUNT,
  GF_DISPLAY,
  ACCOUNT_CODE1,
  ACCOUNT_CODE2,
  ACCOUNT_CODE3,
  GF_FEE_SCHEDULE,
  REC_DATE,
  REC_FUL_NAM,
  GF_UNIT,
  INVOICE,
  FEE_NOTES,
  FEE_SCHEDULE_VERSION,
  INVOICE_CUSTOMIZED_NBR,
  TT_FEE_CODE,
  TT_FEE_DESC,
  GF_FEE_TYPE_ALLOCATION,
  GF_L1_ALLOCATION,
  GF_L2_ALLOCATION,
  GF_L3_ALLOCATION,
  VOID_FLAG,
  GF_FEE_APPLY_DATE,
  INV_DATE,
  INV_REC_DATE,
  INV_REC_FUL_NAM
FROM AATABLE_PERMIT_FEE
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_FEEALLOCATION')
BEGIN
DROP VIEW AASTD_PERMIT_FEEALLOCATION
END
go
CREATE VIEW AASTD_PERMIT_FEEALLOCATION AS
SELECT
PERMITNUM,
FEE_KEY,
PAY_KEY,
FEE_ALLOCATION
FROM AATABLE_PERMIT_FEEALLOCATION
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_GUIDESHEET')
BEGIN
DROP VIEW AASTD_PERMIT_GUIDESHEET
END
go
CREATE VIEW AASTD_PERMIT_GUIDESHEET AS
SELECT
  PERMITNUM,
  INSP_NUMBER,
  GUIDE_KEY,
  TT_ITEM_STATUS,
  COMMENTS,
  SCORE,
  TT_GUIDE_TYPE,
  TT_GUIDE_ITEM,
  TEAM_NAME,
  FLOOR,
  FLOOR_UNIT,
  HISTORICAL_GUIDE_TEXT,
  HISTORICAL_GUIDE_ITEM_STATUS_GROUP 
FROM AATABLE_PERMIT_GUIDESHEET
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_HISTORY')
BEGIN
DROP VIEW AASTD_PERMIT_HISTORY
END
go
CREATE VIEW AASTD_PERMIT_HISTORY AS
SELECT
  PERMITNUM,
  CONTRACTOR_VALUATION,
  DATEOPENED,
  EXPIRATION_DATE,
  EXPIRATION_STATUS,
  WORK_DESC,
  APP_NAME,
  HOUSE_COUNT,
  BUILDING_COUNT,
  PUBLIC_OWNED,
  CONST_TYPE_CODE,
  SHORT_NOTES,
  ASGN_DEPT,
  ASGN_STAFF,
  ASGN_DATE,
  COMPLETED_DEPT,
  COMPLETED_BY,
  COMPLETED_DATE,
  SCHEDULED_DATE,
  PRIORITY,
  TOTAL_JOB_COST,
  CLOSED_DATE,
  CLOSED_BY,
  IVR_TRACKING_NUM,
  CREATED_BY,
  REPORTED_CHANNEL,
  CREATED_BY_DEPT,
  FIRST_ISSUED_DATE,
  ANONYMOUS_FLAG,
  REFERENCE_TYPE,
  APPEARANCE_DAYOFWEEK,
  APPEARANCE_DATE,
  BOOKING_FLAG,
  DEFENDANT_SIGNATURE_FLAG,
  ENFORCE_OFFICER_ID,
  ENFORCE_OFFICER_NAME,
  INFRACTION_FLAG,
  INSPECTOR_ID,
  MISDEMEANOR_FLAG,
  OFFENCE_WITNESSED_FLAG,
  INSPECTOR_NAME,
  ENFORCE_DEPT,
  INSPECTOR_DEPT,
  VALUATION_MULTIPLIER,
  VALUATION_EXTRA_AMT,
  LAST_AUDIT_DATE,
  APP_STATUS_DATE,
  DELEGATE_USER_ID,
  TT_RECORD_STATUS,
  TT_RECORD,
  BALANCE,
  TOTAL_FEE,
  TOTAL_PAY,
  LAST_UPDATE_BY,
  LAST_UPDATE_DATE
FROM AATABLE_PERMIT_HISTORY
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_INSP')
BEGIN
DROP VIEW AASTD_PERMIT_INSP
END
go
CREATE VIEW AASTD_PERMIT_INSP AS
SELECT
  PERMITNUM,
  INSPDATE,
  INSPSCHEDDATE,
  INSPREQDATE,
  INSP_NUMBER,
  INSP_REQUIRED,
  PHONE_NUM,
  LATITUDE,
  LONGITUDE,
  INSP_RESULT_COMM,
  INSP_SCHED_COMM,
  SD_OVERTIME,
  DISPLAY_IN_ACA,
  TT_INSPECTION,
  TT_INSPECTION_STATUS,
  CONTACT_NBR,
  INSP_SEQ_NBR,
  USER_ID,
  ORDER_BY,
  G6_ACT_T1,
  G6_ACT_T2,
  G6_ACT_END_T1,
  G6_ACT_END_T2,
  G6_ACT_TT,
  ESTIMATED_START_TIME,
  ESTIMATED_END_TIME,
  G6_DESI_DD,
  G6_DESI_TIME,
  G6_DESI_TIME2,
  CONTACT_PHONE_NUM,
  CONTACT_PHONE_NUM_IDD,
  CONTACT_FNAME,
  CONTACT_MNAME,
  CONTACT_LNAME,
  G6_REQ_PHONE_NUM_IDD,
  G6_REQ_PHONE_NUM,
  MAJOR_VIOLATION_COUNT,
  UNIT_NBR,
  GRADE,
  TOTAL_SCORE,
  VEHICLE_NUM,
  G6_MILE_T1 ,
  G6_MILE_T2 ,
  G6_MILE_TT ,
  INSP_CANCELLED,
  INSP_PENDING,
  CLIENT_UNIQUE_ID 
FROM AATABLE_PERMIT_INSP
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_INSPDISTRICTS')
BEGIN
DROP VIEW AASTD_PERMIT_INSPDISTRICTS
END
go
CREATE VIEW AASTD_PERMIT_INSPDISTRICTS AS
SELECT
  PERMITNUM,
  DIST_TYPE,
  DIST_KEY,
  INSP_DISTRICT
FROM AATABLE_PERMIT_INSPDISTRICTS
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_PARCEL')
BEGIN
DROP VIEW AASTD_PERMIT_PARCEL
END
go
CREATE VIEW AASTD_PERMIT_PARCEL AS
SELECT
  PERMITNUM,
  PARCELNUM,
  BOOK,
  PAGE,
  PARCEL,
  LOT,
  BLOCK,
  TRACT,
  LEGAL_DESC,
  PARCEL_AREA,
  PLAN_AREA,
  CENSUS_TRACT,
  COUNCIL_DISTRICT,
  SUPERVISOR_DISTRICT,
  INSPECTION_DISTRICT,
  LAND_VALUE,
  IMPROVED_VALUE,
  EXEMPT_VALUE,
  MAP_REFERENCE,
  MAP_NUMBER,
  SUBDIVISION,
  PRIMARY_FLAG,
  TOWNSHIP,
  RANGE,
  SECTION,
  EXT_PARCEL_UID
FROM AATABLE_PERMIT_PARCEL
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_PEOPLE')
BEGIN
DROP VIEW AASTD_PERMIT_PEOPLE
END
go
CREATE VIEW AASTD_PERMIT_PEOPLE AS
SELECT
  PERMITNUM,
  TT_CONTACT_TYPE,
  CONTACT_RELATIONSHIP,
  ISPRIMARY,
  LIC_NUM,
  LIC_TYPE,
  NAME,
  FNAME,
  MNAME,
  LNAME,
  BUS_NAME,
  ADDR1,
  ADDR2,
  ADDR3,
  CITY,
  STATE,
  ZIP,
  PH1,
  PH2,
  FAX,
  EMAIL,
  COMMENTS,
  TITLE,
  PH3,
  COUNTRY_CODE,
  NOTIFY,
  NAME_SUFFIX,
  BUS_LIC,
  LIC_ORIGINAL_ISSUE_DATE,
  EXPIRATION_DATE,
  RENEWAL_DATE,
  MAIL_ADDR1,
  MAIL_ADDR2,
  MAIL_ADDR3,
  MAIL_CITY,
  MAIL_STATE,
  MAIL_ZIP,
  MAIL_COUNTRY,
  OWNER_TYPE,
  GENDER,
  SALUTATION,
  PO_BOX,
  BUS_NAME2,
  BIRTH_DATE,
  PH1_COUNTRY_CODE,
  PH2_COUNTRY_CODE,
  FAX_COUNTRY_CODE,
  PH3_COUNTRY_CODE,
  TRADE_NAME,
  CONTACT_TYPE_FLAG,
  SOCIAL_SECURITY_NUMBER,
  FEDERAL_EMPLOYER_ID_NUM,
  CONTRA_TYPE_FLAG,
  LIC_BOARD,
  B1_ID,
  CONT_LIC_BUS_NAME,
  B1_ACCESS_LEVEL,
  BIRTH_CITY,
  BIRTH_STATE,
  BIRTH_REGION,
  B1_CONTACT_NBR,
  DECEASED_DATE,
  DRIVER_LIC_NBR,
  DRIVER_LIC_STATE,
  RACE,
  PASSPORT_NBR,
  STATE_ID_NBR,
  G1_CONTACT_NBR,
  LIC_STATE
FROM AATABLE_PERMIT_PEOPLE
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_PEOPLEATTRIB')
BEGIN
DROP VIEW AASTD_PERMIT_PEOPLEATTRIB
END
go
CREATE VIEW AASTD_PERMIT_PEOPLEATTRIB AS
SELECT
  PERMITNUM,
  ATTRIB_KEY,
  ATTRIB_TEMP_NAME,
  ATTRIB_TYPE,
  ATTRIB_NAME,
  NAME,
  ATTRIB_VALUE
FROM AATABLE_PERMIT_PEOPLEATTRIB
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_PEOPLELICTABLE')
BEGIN
DROP VIEW AASTD_PERMIT_PEOPLELICTABLE
END
go
CREATE VIEW AASTD_PERMIT_PEOPLELICTABLE AS
SELECT
  PERMITNUM,
  LIC_NUM,
  LIC_TYPE,
  TABLE_NAME,
  COLUMN_NAME,
  ROW_NUM,
  COLUMN_NUM,
  TABLE_VALUE
FROM AATABLE_PERMIT_PEOPLELICTABLE
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_PROJECTS')
BEGIN
DROP VIEW AASTD_PERMIT_PROJECTS
END
go
CREATE VIEW AASTD_PERMIT_PROJECTS AS
SELECT
  PARENTACTIVITYNUM,
  CHILDACTIVITYNUM,
  RELATIONSHIP,
  STATUS
FROM AATABLE_PERMIT_PROJECTS
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_STATUS')
BEGIN
DROP VIEW AASTD_PERMIT_STATUS
END
go
CREATE VIEW AASTD_PERMIT_STATUS AS
SELECT
  PERMITNUM,
  STATUS,
  STATUS_DATE,
  STATUS_COMMENT, 
  USER_ID,
  ORDER_BY
FROM AATABLE_PERMIT_STATUS
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_STRU_ESTA')
BEGIN
DROP VIEW AASTD_PERMIT_STRU_ESTA
END
go
CREATE VIEW AASTD_PERMIT_STRU_ESTA AS
SELECT
  PERMITNUM,
  L1_NUMBER,
  L1_GROUP,
  L1_TYPE
FROM AATABLE_PERMIT_STRU_ESTA
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_WORKFLOW')
BEGIN
DROP VIEW AASTD_PERMIT_WORKFLOW
END
go
CREATE VIEW AASTD_PERMIT_WORKFLOW AS
SELECT
  PERMITNUM,
  TASKUPDATED,
  COMMENTS,
  ASGN_DATE,
  DUE_DATE,
  TT_WORKFLOW_TASK,
  TT_WORKFLOW_STATUS,
  USER_ID,
  ID,
  SD_HOURS_SPENT,
  SD_BILLABLE,
  SD_OVERTIME,
  ESTIMATED_HOURS,
  ASGN_EMAIL_DISPLAY_FOR_ACA,
  RESTRICT_COMMENT_FOR_ACA,
  RESTRICT_ROLE,
  TASK_UNIQUE_ID 
FROM AATABLE_PERMIT_WORKFLOW
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_TRUST_ACCOUNT_TRANS')
BEGIN
DROP VIEW AASTD_TRUST_ACCOUNT_TRANS
END
go
CREATE VIEW AASTD_TRUST_ACCOUNT_TRANS AS
SELECT
  ACCOUNT_ID,
  TRANS_TYPE,
  TRANS_AMOUNT,
  TRANS_DATE,
  TRANS_BY,
  TARGET_ACCT_ID,
  PERMITNUM,
  PAY_KEY
FROM AATABLE_TRUST_ACCOUNT_TRANS
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_TRUST_ACCOUNTS')
BEGIN
DROP VIEW AASTD_TRUST_ACCOUNTS
END
go
CREATE VIEW AASTD_TRUST_ACCOUNTS AS
SELECT
  ACCOUNT_ID,
  ACCOUNT_BALANCE,
  LEDGER_ACCOUNTNUM,
  ACCT_DESC,
  ACCT_STATUS,
  ACCT_OVERDRAFT,
  ACCT_OVERDRAFTLIMIT,
  THRESHOLD_AMT
FROM AATABLE_TRUST_ACCOUNTS
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_TRUST_ACCT_PEOPLE_LINKS')
BEGIN
DROP VIEW AASTD_TRUST_ACCT_PEOPLE_LINKS
END
go
CREATE VIEW AASTD_TRUST_ACCT_PEOPLE_LINKS AS
SELECT
ACCOUNT_ID,
CONTACT_NBR,
LIC_NBR,
LIC_TYPE,
LIC_STATE
FROM AATABLE_TRUST_ACCT_PEOPLE_LINKS
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_AUDIT_SETS')
BEGIN
DROP VIEW AASTD_PERMIT_AUDIT_SETS
END
GO

CREATE VIEW AASTD_PERMIT_AUDIT_SETS
AS
SELECT
PERMITNUM,
SET_ID
FROM AATABLE_PERMIT_AUDIT_SETS
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_permit_TaskSpecAdHoc')
BEGIN
DROP VIEW AASTD_permit_TaskSpecAdHoc
END
GO

CREATE VIEW AASTD_PERMIT_TASKSPECADHOC
AS
SELECT
PERMITNUM,
TASK_SPEC_CODE,
TASK_SPEC_TYPE,
TASK_SPEC_NAME,
TASK_SPEC_VALUE,
PROCESS_CODE,
TASK_DESC,
SD_STP_NUM
FROM AATABLE_PERMIT_TASKSPECADHOC
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_pos_transaction')
BEGIN
DROP VIEW AASTD_pos_transaction
END
GO 

CREATE VIEW AASTD_pos_transaction 
AS
SELECT
	tran_key, -- Loaded it to f4pos_transaction.batch_transaction_nbr
	module_name,
	pos_trans_type 
FROM AATABLE_pos_transaction
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_pos_trans_fee')
BEGIN
DROP VIEW AASTD_pos_trans_fee
END
GO

CREATE VIEW AASTD_pos_trans_fee 
AS
SELECT
	tran_key, 
	fee_key,
	gf_cod,
	gf_des,
	gf_unit,
	gf_fee,
	gf_fee_apply_date,
	gf_sub_group,
	gf_fee_schedule,
	gf_fee_schedule_version,
	fee_notes
FROM AATABLE_pos_trans_fee
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_pos_trans_pay')
BEGIN
DROP VIEW AASTD_pos_trans_pay
END
GO 

CREATE VIEW AASTD_pos_trans_pay
AS
SELECT
	tran_key,
	pay_key,
	payment_status,
	payment_amount,
	payment_date,
	cashier_id,
	payment_method,
	payment_ref_nbr,
	payee,
	payee_address,
	payee_phone,
	cc_auth_code,
	payment_comment,
	HIST_RECEIPT_NBR,
	register_nbr,
	VOID_DATE,
	VOID_BY
FROM AATABLE_pos_trans_pay
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_TRUST')
BEGIN
DROP VIEW AASTD_PERMIT_TRUST
END
GO

CREATE VIEW AASTD_PERMIT_TRUST
AS
SELECT
PERMITNUM,
TRUST_ACCOUNT_ID
FROM AATABLE_PERMIT_TRUST
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_permit_time_accounting')
BEGIN
DROP VIEW AASTD_permit_time_accounting
END
GO

CREATE VIEW AASTD_permit_time_accounting
AS
SELECT
    permitnum,
    tt_time_group_name,
    tt_time_type_name,
    billable_flag,
    log_date,
    time_start,
    time_end,
    time_elapsed,
    total_minutes,
    materials_desc,
    materials_cost,
    Mileage_start,
    Mileage_end,
    Milage_total,
    vehicle_id,
    entry_rate,
    entry_pct,
    entry_cost,
    created_date,
    created_by,
    notation,
    group_seq_nbr,
    entity_id,
    entity_type, 
    user_name,
    Unique_Id,
	TIME_LOG_STATUS,
	RECORD_TYPE 
FROM AATABLE_permit_time_accounting
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_WORKFLOWADHOC')
BEGIN
DROP VIEW AASTD_PERMIT_WORKFLOWADHOC
END
GO

CREATE VIEW AASTD_permit_workflowAdHoc 
AS
SELECT
  PERMITNUM,
  TASK_DESC,
  TASK_STATUS,
  TASKUPDATED,
  FNAME,
  MNAME,
  LNAME,
  COMMENTS,
  PROCESS_CODE,
  CHECK_LEVEL1,
  CHECK_LEVEL2, 
  G6_ASGN_DD,
  B1_DUE_DD,
  SD_DUE_DAY,
  SD_NOTE,
  SD_STP_NUM,
  ASGN_AGENCY_CODE,
  ASGN_BUREAU_CODE,
  ASGN_DIVISION_CODE,
  ASGN_GROUP_CODE,
  ASGN_SECTION_CODE,
  ASGN_OFFICE_CODE,
  ASGN_FNAME,
  ASGN_MNAME,
  ASGN_LNAME
FROM AATABLE_permit_workflowAdHoc
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_COSTING_AMS')
BEGIN
DROP VIEW AASTD_PERMIT_COSTING_AMS
END
GO 
CREATE  VIEW AASTD_PERMIT_COSTING_AMS 
AS
SELECT
	PERMITNUM,
	COST_NAME,
	COST_DATE,
	COST_TYPE,
	COST_ITEM,
	COST_FIX,
	COST_FACTOR,
	COST_UNIT_COST,
	COST_UNIT_TYPE,
	COST_QUANTITY,
	COST_ITEM_TOTAL,
	COST_COMMENTS,
	UPDATED_BY,
	UPDATED_DATE,
	COST_STATUS,
	START_TIME,
	END_TIME,
	RELATED_ASGN_NBR,
	TASK_CODE,
	TASK_CODE_INDEX
FROM AATABLE_PERMIT_COSTING_AMS
GO


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_ASSET_AMS')
BEGIN
DROP VIEW AASTD_PERMIT_ASSET_AMS
END
GO

CREATE VIEW  AASTD_PERMIT_ASSET_AMS 
AS
SELECT
PERMITNUM,
ASSET_ID,
ASSET_GROUP,
ASSET_TYPE,
WOASSET_ORDER,
WOASSET_COMPLETE,
WOASSET_COMPLETE_DATE,
WOASSET_SHORT_NOTES
FROM AATABLE_PERMIT_ASSET_AMS
GO


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_TASK_AMS')
BEGIN
DROP VIEW AASTD_PERMIT_TASK_AMS
END
GO

CREATE VIEW  AASTD_PERMIT_TASK_AMS
AS
SELECT
	PERMITNUM,
	TASK_CODE,
	TASK_CODE_INDEX,
	TASK_DESCRIPTION,
	OPERATION_PROCEDURE,
	ESTIMATE_EFFORT,
	DURATION_UNIT,
	ACTUAL_EFFORT,
	COMPLETE_DATE,
	COMPLETE_BY,
	COMMENTS,
	TASK_ORDER
FROM AATABLE_PERMIT_TASK_AMS
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_COST_DIST')
BEGIN
DROP VIEW AASTD_PERMIT_COST_DIST 
END
GO

CREATE VIEW AASTD_PERMIT_COST_DIST 
AS
SELECT
	PERMITNUM,
	ASSET_ID,
	ASSET_HIST_TYPE,
	PART_NUMBER,
	COST_NAME
FROM AATABLE_PERMIT_COST_DIST
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'aastd_permit_part_ams')
BEGIN
DROP VIEW aastd_permit_part_ams
END
go

create view aastd_permit_part_ams 
as
select
	permitnum,
	transaction_type,
	transaction_date,
	quantity,
	Part_number,
	location_name,
	Part_bin,
	taxable,
	part_brand,
	part_description,
	Part_type,
	unit_of_measurement,
	unit_of_cost,
	comments,
	last_updated_date,
	last_updated_by
from aatable_permit_part_ams
go


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_REFER_PEOPLE')
BEGIN
DROP VIEW AASTD_REFER_PEOPLE 
END
GO

CREATE VIEW AASTD_REFER_PEOPLE 
AS
SELECT 
CONTACT_NBR,
TT_CONTACT_TYPE,
TITLE,
FNAME,
MNAME,
LNAME,
NAME_SUFFIX,
FULL_NAME,
BUS_NAME,
ADDR1,
ADDR2,
ADDR3,
CITY,
STATE,
ZIP,
COUNTRY,
PH1,
PH2,
FAX,
EMAIL,
G1_ID,
G1_FLAG,
COMMENTS,
RELATION,
G1_PREFERRED_CHANNEL,
COUNTRY_CODE,
GA_IVR_PIN,
PH3,
SALUTATION,
GENDER,
POST_OFFICE_BOX,
BIRTH_DATE,
PH1_COUNTRY_CODE,
PH2_COUNTRY_CODE,
PH3_COUNTRY_CODE,
FAX_COUNTRY_CODE,
SOCIAL_SECURITY_NUMBER,
FEDERAL_EMPLOYER_ID_NUM,
TRADE_NAME,
CONTACT_TYPE_FLAG,
BUSINESS_NAME2,
BIRTH_CITY,
BIRTH_STATE,
BIRTH_REGION,
G1_RACE,
DECEASED_DATE,
PASSPORT_NBR,
DRIVER_LICENSE_NBR,
DRIVER_LICENSE_STATE,
STATE_ID_NBR
FROM AATABLE_REFER_PEOPLE
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_REFER_PEOPLECONDIT')
BEGIN
DROP VIEW AASTD_REFER_PEOPLECONDIT
END
GO


CREATE VIEW AASTD_REFER_PEOPLECONDIT
AS
SELECT 
  ENTITY_TYPE,
  ENTITY_ID,
  L1_CON_NBR,
  CON_COMMENT,
  CON_DES,
  CON_EFF_DD1,
  CON_EXPIR_DD,
  CON_IMPACT_CODE,
  CON_REF_NUM1,
  CON_REF_NUM2,
  CON_STATUS,
  CON_TYP,
  CON_LONG_COMMENT,
  CON_DIS_CON_NOTICE,
  CON_INC_CON_NAME,
  CON_INC_SHORT_DESC,
  CON_INHERITABLE,
  CON_STATUS_TYP,
  CON_GROUP,
  CON_DIS_NOTICE_ACA,
  CON_DIS_NOTICE_ACA_FEE,
  R3_CON_RESOLUTION_ACTION,
  R3_CON_PUBLIC_DIS_MESSAGE,
  PRIORITY,
  ADDITIONAL_INFORMATION
FROM AATABLE_REFER_PEOPLECONDIT
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_REFER_PEOPLEADDR')
BEGIN
DROP VIEW AASTD_REFER_PEOPLEADDR
END
GO

CREATE VIEW AASTD_REFER_PEOPLEADDR
AS
SELECT 
  ENTITY_TYPE,
  ENTITY_ID,
  ADDRESS_TYPE,
  EFF_DATE,
  EXPR_DATE,
  RECIPIENT,
  FULL_ADDRESS,
  ADDRESS1,
  ADDRESS2,
  ADDRESS3,
  HSE_NBR_START,
  HSE_NBR_END,
  STR_DIR,
  STR_PREFIX,
  STR_NAME,
  STR_SUFFIX,
  UNIT_TYPE,
  UNIT_START,
  UNIT_END,
  STR_SUFFIX_DIR,
  COUNTRY_CODE,
  CITY,
  STATE,
  ZIP,
  PHONE,
  PHONE_COUNTRY_CODE,
  FAX,
  FAX_COUNTRY_CODE,
  HSE_NBR_ALPHA_START,
  HSE_NBR_ALPHA_END,
  LEVEL_PREFIX,
  LEVEL_NBR_START,
  LEVEL_NBR_END,
  VALIDATE_ADDR_FLAG,
  PRIMARY_ADDR_FLAG
FROM AATABLE_REFER_PEOPLEADDR

GO

------------------------------------------------------------

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_AMS_MASTER')
BEGIN
DROP VIEW AASTD_AMS_MASTER
END
GO

CREATE VIEW AASTD_AMS_MASTER
AS
SELECT 
 ASSET_ID                 ,
 ASSET_HIST_TYPE          ,
 ASSET_GROUP              ,
 ASSET_TYPE               ,
 CLASS_TYPE				  ,
 ASSET_DESC               ,
 ASSET_STATUS             ,
 ASSET_STATUS_DATE        ,
 ASSET_COMMENTS           ,
 START_VALUE              ,
 DATE_OF_SERVICE          ,
 USEFUL_LIFE              ,
 SALVAGE_VALUE            ,
 CURRENT_VALUE            ,
 DEPRECIATION_START_DATE  ,
 DEPRECIATION_END_DATE    ,
 DEPRECIATION_AMOUNT      ,
 DEPRECIATION_VALUE       ,
 ASSET_START_ID           ,
 ASSET_END_ID             ,
 DEPENDENCIES_FLAG        ,
 ASSET_SIZE               ,
 ASSET_SIZE_UNIT          ,
 RES_ID					  ,
 G1_ASSET_NAME			  
FROM AATABLE_AMS_MASTER
GO



IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_AMS_ATTRIBUTE')
BEGIN
DROP VIEW AASTD_AMS_ATTRIBUTE
END
GO

CREATE VIEW AASTD_AMS_ATTRIBUTE
AS
SELECT 
	ASSET_ID                 ,
	ASSET_HIST_TYPE          ,
	ASSET_ATTRIB_TEMP_NAME   ,
	ASSET_ATTRIB_NAME        ,
	ASSET_ATTRIB_VALUE       ,
	IS_HIDDEN				 
FROM AATABLE_AMS_ATTRIBUTE
GO


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_AMS_ATTRIBUTE_TABLE')
BEGIN
DROP VIEW AASTD_AMS_ATTRIBUTE_TABLE
END
GO

CREATE VIEW AASTD_AMS_ATTRIBUTE_TABLE
AS
SELECT 
	ASSET_ID        ,
	ASSET_HIST_TYPE ,
	ASSET_ATTRIB_TAB_NAME ,
	ASSET_ATTRIB_NAME,
	ATTRIB_ROW_INDEX,
	ASSET_ATTRIB_VALUE	
FROM AATABLE_AMS_ATTRIBUTE_TABLE
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_AMS_ASSET_ASSET')
BEGIN
DROP VIEW AASTD_AMS_ASSET_ASSET
END
GO

CREATE VIEW AASTD_AMS_ASSET_ASSET
AS
SELECT 
	PARENT_ASSET_ID        ,
	PARENT_ASSET_HIST_TYPE ,
	CHILD_ASSET_ID         ,
	CHILD_ASSET_HIST_TYPE  
FROM AATABLE_AMS_ASSET_ASSET
GO


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_REFER_PEOPLE_LINKS')
BEGIN
DROP VIEW AASTD_REFER_PEOPLE_LINKS
END
GO

CREATE VIEW AASTD_REFER_PEOPLE_LINKS
AS
SELECT 
	CONTACT_NBR,
	ENT_TYPE,
	ENT_ID1,
	ENT_ID2,  
	ENT_ID3,  
	PRIMARY_FLAG,  
	comments,  
	START_DATE,  
	END_DATE
FROM AATABLE_REFER_PEOPLE_LINKS
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_LIC_PROF')
BEGIN
DROP VIEW AASTD_LIC_PROF
END
go
CREATE VIEW AASTD_LIC_PROF
AS
SELECT 
	serv_prov_code  ,
lic_nbr             ,
lic_status          ,
lic_state           ,
tt_lic_type            ,
bus_name            ,
lic_orig_iss_dd     ,
last_renewal_dd     ,
lic_expir_dd        ,
cae_fname           ,
cae_mname           ,
cae_lname           ,
address1            ,
address2            ,
city                ,
state               ,
zip			        ,
phone1			    ,
phone2			    ,
fax			        ,
email			    ,
lic_comment		    ,
ins_co_name		    ,
ins_amount		    ,
ins_policy_no		,
ins_exp_dt		    ,
bus_lic			    ,
bus_lic_exp_dt		,
last_update_dd		,	
lic_seq_nbr		    ,
rec_date		    ,
rec_ful_nam		    ,
rec_flag		    ,
lic_board 	        ,
address3            ,
wc_exempt           ,
wc_policy_no        ,
wc_eff_dt           ,
wc_exp_dt           ,
wc_canc_dt          ,
suffix_name         ,
country             ,
county_code         ,
wc_ins_co_code      ,
contr_lic_no        ,
cont_lic_bus_name       ,
ga_ivr_pin              ,
l1_salutation	          ,		
l1_gender	              ,		
l1_post_office_box      ,		
bus_name2               ,		
l1_birth_date          ,
phone1_country_code     ,
phone2_country_code    ,
fax_country_code        ,	
lic_type_flag                ,
lic_social_security_nbr       ,	
lic_federal_employer_id_nbr   ,	
phone3                        ,	
phone3_country_code           ,	
aca_permission               ,		
l1_title                      ,		
past_days                     
FROM AATABLE_LIC_PROF
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_LIC_PROF_ATTR')
BEGIN
DROP VIEW AASTD_LIC_PROF_ATTR
END
go

CREATE VIEW AASTD_LIC_PROF_ATTR
AS
SELECT 
serv_prov_code      ,
lic_nbr                 ,
lic_type                ,
attrib_temp_name        ,
attrib_name             ,
attrib_value     
FROM AATABLE_LIC_PROF_ATTR
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_LIC_PROF_ATTACH')
BEGIN
DROP VIEW AASTD_LIC_PROF_ATTACH
END
go

CREATE VIEW AASTD_LIC_PROF_ATTACH
AS
SELECT 
serv_prov_code		    ,
lic_nbr			        ,
lic_type		        ,
group_name		        ,
table_name		        ,
column_name		        ,
row_num			        ,
attach_value
FROM AATABLE_LIC_PROF_ATTACH
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_TEMPLATE_ASI')
BEGIN
DROP VIEW AASTD_TEMPLATE_ASI
END
go

CREATE VIEW AASTD_TEMPLATE_ASI
AS
SELECT 
ENTITY_TYPE 		    ,
ENTITY_ID 			        ,
GROUP_CODE 		        ,
ASI_SUB_GROUP_CODE  		        ,
FIELD_NAME 		        ,
FIELD_VALUE 
FROM AATABLE_TEMPLATE_ASI
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_TEMPLATE_ASIT')
BEGIN
DROP VIEW AASTD_TEMPLATE_ASIT
END
go

CREATE VIEW AASTD_TEMPLATE_ASIT
AS
SELECT 
ENTITY_TYPE 		    ,
ENTITY_ID 			        ,
GROUP_CODE  		        ,
ASI_SUB_GROUP_CODE    		        ,
FIELD_NAME  		        ,
FIELD_VALUE  				,
ROW_INDEX 
FROM AATABLE_TEMPLATE_ASIT
GO

-- AASTD_PERMIT_PAYMENTS
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_PAYMENTS')
BEGIN
DROP VIEW AASTD_PERMIT_PAYMENTS
END
go

CREATE VIEW AASTD_PERMIT_PAYMENTS
AS
SELECT
PERMITNUM,
PAY_KEY,
PAYMENT_METHOD,
PAYMENT_REF_NBR,
CC_TYPE,
PAYEE,
PAYMENT_DATE,
PAYMENT_AMOUNT,
TRANSACTION_CODE,
TRANSACTION_NBR,
PAYMENT_COMMENT,
CASHIER_ID,
REGISTER_NBR,
REC_DATE,
REC_FUL_NAM,
ACCT_ID,
PAYEE_ADDRESS,
PAYEE_PHONE,
CC_AUTH_CODE,
PAYEE_PHONE_IDD,
PAYMENT_RECEIVED_CHANNEL,
CHECK_NUMBER,
CHECK_TYPE,
DRIVER_LICENSE,
CHECK_HOLDER_NAME,
CHECK_HOLDER_EMAIL,
PHONE_NUMBER,
COUNTRY,
STATE,
CITY,
STREET,
ZIP,
REASON,
PAYEE_TYPE,
HIST_RECEIPT_NBR,
VOID_BY,
VOID_DATE,
payment_pay_key 
FROM AATABLE_PERMIT_PAYMENTS
GO

-- AASTD_PERMIT_RECEIPTS
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = N'AASTD_PERMIT_RECEIPTS')
BEGIN
DROP VIEW AASTD_PERMIT_RECEIPTS
END
go

CREATE VIEW AASTD_PERMIT_RECEIPTS
AS
SELECT
HIST_RECEIPT_NBR,
RECEIPT_DATE,
CASHIER_ID,
REGISTER_NBR,
RECEIPT_AMOUNT,
RECEIPT_COMMENT,
RECEIPT_STATUS,
TRANSACTION_CODE,
TRANSACTION_NBR,
REC_DATE,
REC_FUL_NAM,
TTERMINAL_ID,
WORKSTATION_ID
FROM AATABLE_PERMIT_RECEIPTS
GO